/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AddEmojisData {
    /**
    * Specifies the unique ID of the emoji category that a list of new emojis belong to.
    */
    'emojiCategoryId': number;
    /**
    * Specifies a list of one or more new emojis to register.
    */
    'emojis': Array<any>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "emojiCategoryId",
            "baseName": "emoji_category_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "emojis",
            "baseName": "emojis",
            "type": "Array<any>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AddEmojisData.attributeTypeMap;
    }

    public constructor() {
    }
}

