/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V3ApplicationsSettingsByChannelCustomTypeCustomTypeBanBannedList } from './V3ApplicationsSettingsByChannelCustomTypeCustomTypeBanBannedList';
import { HttpFile } from '../http/http';

export class BanUsersInChannelsWithCustomChannelTypeData {
    'bannedList': Array<V3ApplicationsSettingsByChannelCustomTypeCustomTypeBanBannedList>;
    'onDemandUpsert'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bannedList",
            "baseName": "banned_list",
            "type": "Array<V3ApplicationsSettingsByChannelCustomTypeCustomTypeBanBannedList>",
            "format": ""
        },
        {
            "name": "onDemandUpsert",
            "baseName": "on_demand_upsert",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BanUsersInChannelsWithCustomChannelTypeData.attributeTypeMap;
    }

    public constructor() {
    }
}

