/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ChooseWhichEventsToSubscribeToResponseWebhook {
    'enabled'?: boolean;
    'url'?: string;
    'includeMembers'?: boolean;
    'enabledEvents'?: Array<string>;
    'includeUnreadCount'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "includeMembers",
            "baseName": "include_members",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "enabledEvents",
            "baseName": "enabled_events",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "includeUnreadCount",
            "baseName": "include_unread_count",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChooseWhichEventsToSubscribeToResponseWebhook.attributeTypeMap;
    }

    public constructor() {
    }
}

