/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ConfigureAutoEventDataAutoEventMessage {
    'userLeave'?: any;
    'userJoin'?: any;
    'channelCreate'?: any;
    'channelChange'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userLeave",
            "baseName": "user_leave",
            "type": "any",
            "format": ""
        },
        {
            "name": "userJoin",
            "baseName": "user_join",
            "type": "any",
            "format": ""
        },
        {
            "name": "channelCreate",
            "baseName": "channel_create",
            "type": "any",
            "format": ""
        },
        {
            "name": "channelChange",
            "baseName": "channel_change",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConfigureAutoEventDataAutoEventMessage.attributeTypeMap;
    }

    public constructor() {
    }
}

