/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateBotData {
    /**
    * Specifies the unique ID of the bot. The length is limited to 80 characters.
    */
    'botUserid': string;
    /**
    * Specifies the bot's nickname. The length is limited to 80 characters.
    */
    'botNickname': string;
    /**
    * Specifies the URL of the bot's profile image. The size is limited to 2,048 characters.
    */
    'botProfileUrl': string;
    /**
    * Specifies the type of the bot that you can specify for categorization. The length is limited to 128 characters.
    */
    'botType': string;
    /**
    * Specifies the server URL where bot is located to receive all events, requests, and data forwarded from an application. For security reasons, it is highly recommended that you use an SSL server. The length is limited to 1,024 characters.
    */
    'botCallbackUrl': string;
    /**
    * In the channels of where the bot is a member, determines whether to only forward the messages with the specific conditions to the bot or forword all messages to the bot, for privacy concerns. If set to true, only messages that start with a '/' or mention the bot_userid are forwarded to the bot. If set to false, all messages are forwarded.
    */
    'isPrivacyMode': boolean;
    /**
    * Determines whether to mark the bot's message as read upon sending it. (Default: true)
    */
    'enableMarkAsRead'?: boolean;
    /**
    * Determines whether to include information about the members of each channel in a callback response. (Default: false)
    */
    'showMember'?: boolean;
    'channelInvitationPreference'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "botUserid",
            "baseName": "bot_userid",
            "type": "string",
            "format": ""
        },
        {
            "name": "botNickname",
            "baseName": "bot_nickname",
            "type": "string",
            "format": ""
        },
        {
            "name": "botProfileUrl",
            "baseName": "bot_profile_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "botType",
            "baseName": "bot_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "botCallbackUrl",
            "baseName": "bot_callback_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "isPrivacyMode",
            "baseName": "is_privacy_mode",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "enableMarkAsRead",
            "baseName": "enable_mark_as_read",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "showMember",
            "baseName": "show_member",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "channelInvitationPreference",
            "baseName": "channel_invitation_preference",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateBotData.attributeTypeMap;
    }

    public constructor() {
    }
}

