/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateAGroupChannelResponseSmsFallback {
    'excludeUserIds'?: Array<string>;
    'waitSeconds'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "excludeUserIds",
            "baseName": "exclude_user_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "waitSeconds",
            "baseName": "wait_seconds",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateAGroupChannelResponseSmsFallback.attributeTypeMap;
    }

    public constructor() {
    }
}

