/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GcLeaveChannelData {
    /**
    * Specifies the URL of the channel to leave.
    */
    'channelUrl': string;
    /**
    * Specifies an array of one or more IDs of the users to leave the channel.
    */
    'userIds': Array<string>;
    /**
    * Determines whether to make all members leave the channel. (Default: false)
    */
    'shouldLeaveAll': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channelUrl",
            "baseName": "channel_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "userIds",
            "baseName": "user_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "shouldLeaveAll",
            "baseName": "should_leave_all",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GcLeaveChannelData.attributeTypeMap;
    }

    public constructor() {
    }
}

