/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SendBirdUser } from './SendBirdUser';
import { HttpFile } from '../http/http';

export class GcListMutedUsersResponse {
    'mutedList'?: Array<SendBirdUser>;
    'totalMuteCount'?: number;
    'next'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mutedList",
            "baseName": "muted_list",
            "type": "Array<SendBirdUser>",
            "format": ""
        },
        {
            "name": "totalMuteCount",
            "baseName": "total_mute_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "next",
            "baseName": "next",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GcListMutedUsersResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

