/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GcMarkAllMessagesAsReadData {
    /**
    * Specifies the URL of the target channel.
    */
    'channelUrl': string;
    /**
    * Specifies the ID of the user to mark all messages as read.
    */
    'userId': string;
    /**
    * Specifies the timestamp to be the reference point of marking as read. If specified, the messages received before the specified time are marked as read.
    */
    'timestamp': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channelUrl",
            "baseName": "channel_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GcMarkAllMessagesAsReadData.attributeTypeMap;
    }

    public constructor() {
    }
}

