/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GetDetailedOpenStatusOfAnnouncementByIdResponseOpenStatusInner {
    'userId'?: string;
    'channelUrl'?: string;
    'hasOpened'?: boolean;
    'sentAt'?: number;
    'openAt'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "channelUrl",
            "baseName": "channel_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "hasOpened",
            "baseName": "has_opened",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sentAt",
            "baseName": "sent_at",
            "type": "number",
            "format": ""
        },
        {
            "name": "openAt",
            "baseName": "open_at",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetDetailedOpenStatusOfAnnouncementByIdResponseOpenStatusInner.attributeTypeMap;
    }

    public constructor() {
    }
}

