/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineResponse20041Message } from './InlineResponse20041Message';
import { HttpFile } from '../http/http';

export class InlineResponse20041 {
    'uniqueId'?: string;
    'announcementGroup'?: string;
    'message'?: InlineResponse20041Message;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "uniqueId",
            "baseName": "unique_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "announcementGroup",
            "baseName": "announcement_group",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "InlineResponse20041Message",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20041.attributeTypeMap;
    }

    public constructor() {
    }
}

