/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineResponse20047OgTag } from './InlineResponse20047OgTag';
import { InlineResponse20047SortedMetaarray } from './InlineResponse20047SortedMetaarray';
import { InlineResponse20047User } from './InlineResponse20047User';
import { HttpFile } from '../http/http';

export class InlineResponse20047Messages {
    'messageId'?: number;
    'type'?: string;
    'customType'?: string;
    'channelUrl'?: string;
    'user'?: InlineResponse20047User;
    'mentionType'?: string;
    'mentionedUsers'?: Array<InlineResponse20047User>;
    'isRemoved'?: boolean;
    'message'?: string;
    'translations'?: any;
    'data'?: string;
    'sortedMetaarray'?: Array<InlineResponse20047SortedMetaarray>;
    'ogTag'?: InlineResponse20047OgTag;
    'createdAt'?: number;
    'updatedAt'?: number;
    'file'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "messageId",
            "baseName": "message_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "customType",
            "baseName": "custom_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "channelUrl",
            "baseName": "channel_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "InlineResponse20047User",
            "format": ""
        },
        {
            "name": "mentionType",
            "baseName": "mention_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "mentionedUsers",
            "baseName": "mentioned_users",
            "type": "Array<InlineResponse20047User>",
            "format": ""
        },
        {
            "name": "isRemoved",
            "baseName": "is_removed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "translations",
            "baseName": "translations",
            "type": "any",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "string",
            "format": ""
        },
        {
            "name": "sortedMetaarray",
            "baseName": "sorted_metaarray",
            "type": "Array<InlineResponse20047SortedMetaarray>",
            "format": ""
        },
        {
            "name": "ogTag",
            "baseName": "og_tag",
            "type": "InlineResponse20047OgTag",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "number",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "number",
            "format": ""
        },
        {
            "name": "file",
            "baseName": "file",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20047Messages.attributeTypeMap;
    }

    public constructor() {
    }
}

