/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineResponse20058EmojiCategories } from './InlineResponse20058EmojiCategories';
import { HttpFile } from '../http/http';

export class InlineResponse20058 {
    'emojiCategories'?: Array<InlineResponse20058EmojiCategories>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "emojiCategories",
            "baseName": "emoji_categories",
            "type": "Array<InlineResponse20058EmojiCategories>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20058.attributeTypeMap;
    }

    public constructor() {
    }
}

