/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineResponse20034BannedList } from './InlineResponse20034BannedList';
import { HttpFile } from '../http/http';

export class InlineResponse20034 {
    'bannedList'?: Array<InlineResponse20034BannedList>;
    'totalBanCount'?: number;
    'next'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bannedList",
            "baseName": "banned_list",
            "type": "Array<InlineResponse20034BannedList>",
            "format": ""
        },
        {
            "name": "totalBanCount",
            "baseName": "total_ban_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "next",
            "baseName": "next",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20034.attributeTypeMap;
    }

    public constructor() {
    }
}

