/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineResponse20050Unread } from './InlineResponse20050Unread';
import { HttpFile } from '../http/http';

export class InlineResponse20050 {
    'unread'?: InlineResponse20050Unread;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "unread",
            "baseName": "unread",
            "type": "InlineResponse20050Unread",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20050.attributeTypeMap;
    }

    public constructor() {
    }
}

