/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineResponse20045Statistics } from './InlineResponse20045Statistics';
import { HttpFile } from '../http/http';

export class InlineResponse20045 {
    'statistics'?: Array<InlineResponse20045Statistics>;
    'week'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "statistics",
            "baseName": "statistics",
            "type": "Array<InlineResponse20045Statistics>",
            "format": ""
        },
        {
            "name": "week",
            "baseName": "week",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20045.attributeTypeMap;
    }

    public constructor() {
    }
}

