/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LeaveAChannelRequest {
    /**
    * Specifies an array of one or more IDs of the users to leave the channel.
    */
    'userIds': Array<string>;
    /**
    * Determines whether to make all members leave the channel. (Default: false)
    */
    'shouldLeaveAll'?: boolean;
    /**
    * Determines whether to remove a user from the channel's operator list if the user who is leaving the channel is an operator. (Default: false)
    */
    'shouldRemoveOperatorStatus'?: boolean;
    /**
    * Specifies the reason for leaving a channel. Acceptable values are admin_removed, admin_deleted, admin_deactivated, left_by_own_choice, and channel_operator_removed.
    */
    'reason'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userIds",
            "baseName": "user_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "shouldLeaveAll",
            "baseName": "should_leave_all",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "shouldRemoveOperatorStatus",
            "baseName": "should_remove_operator_status",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LeaveAChannelRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

