/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LeaveMyGroupChannelsData {
    /**
    * Specifies the unique ID of the user to leave all joined group channels.
    */
    'userId': string;
    /**
    * Specifies the custom channel type to make the user leave joined group channels with the corresponding type.
    */
    'customType': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "customType",
            "baseName": "custom_type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LeaveMyGroupChannelsData.attributeTypeMap;
    }

    public constructor() {
    }
}

