/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListPushNotificationContentTemplatesResponseTemplate } from './ListPushNotificationContentTemplatesResponseTemplate';
import { HttpFile } from '../http/http';

export class ListPushNotificationContentTemplatesResponsePushMessageTemplates {
    'templateName'?: string;
    'template'?: ListPushNotificationContentTemplatesResponseTemplate;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "templateName",
            "baseName": "template_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "template",
            "baseName": "template",
            "type": "ListPushNotificationContentTemplatesResponseTemplate",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListPushNotificationContentTemplatesResponsePushMessageTemplates.attributeTypeMap;
    }

    public constructor() {
    }
}

