/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListAllEmojisAndEmojiCategoriesResponseEmojiCategories } from './ListAllEmojisAndEmojiCategoriesResponseEmojiCategories';
import { HttpFile } from '../http/http';

export class ListAllEmojisAndEmojiCategoriesResponse {
    'emojiHash'?: string;
    'emojiCategories'?: Array<ListAllEmojisAndEmojiCategoriesResponseEmojiCategories>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "emojiHash",
            "baseName": "emoji_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "emojiCategories",
            "baseName": "emoji_categories",
            "type": "Array<ListAllEmojisAndEmojiCategoriesResponseEmojiCategories>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListAllEmojisAndEmojiCategoriesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

