/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListMessagesResponseOgTag } from './ListMessagesResponseOgTag';
import { ListMessagesResponseSortedMetaarray } from './ListMessagesResponseSortedMetaarray';
import { ListMessagesResponseUser } from './ListMessagesResponseUser';
import { HttpFile } from '../http/http';

export class ListMessagesResponseMessages {
    'messageId'?: number;
    'type'?: string;
    'customType'?: string;
    'channelUrl'?: string;
    'user'?: ListMessagesResponseUser;
    'mentionType'?: string;
    'mentionedUsers'?: Array<ListMessagesResponseUser>;
    'isRemoved'?: boolean;
    'message'?: string;
    'translations'?: any;
    'data'?: string;
    'sortedMetaarray'?: Array<ListMessagesResponseSortedMetaarray>;
    'ogTag'?: ListMessagesResponseOgTag;
    'createdAt'?: number;
    'updatedAt'?: number;
    'file'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "messageId",
            "baseName": "message_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "customType",
            "baseName": "custom_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "channelUrl",
            "baseName": "channel_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "ListMessagesResponseUser",
            "format": ""
        },
        {
            "name": "mentionType",
            "baseName": "mention_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "mentionedUsers",
            "baseName": "mentioned_users",
            "type": "Array<ListMessagesResponseUser>",
            "format": ""
        },
        {
            "name": "isRemoved",
            "baseName": "is_removed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "translations",
            "baseName": "translations",
            "type": "any",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "string",
            "format": ""
        },
        {
            "name": "sortedMetaarray",
            "baseName": "sorted_metaarray",
            "type": "Array<ListMessagesResponseSortedMetaarray>",
            "format": ""
        },
        {
            "name": "ogTag",
            "baseName": "og_tag",
            "type": "ListMessagesResponseOgTag",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "number",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "number",
            "format": ""
        },
        {
            "name": "file",
            "baseName": "file",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListMessagesResponseMessages.attributeTypeMap;
    }

    public constructor() {
    }
}

