/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListBotsResponseBotsInnerAi } from './ListBotsResponseBotsInnerAi';
import { ListBotsResponseBotsInnerBot } from './ListBotsResponseBotsInnerBot';
import { ListBotsResponseBotsInnerBotStyle } from './ListBotsResponseBotsInnerBotStyle';
import { ListBotsResponseBotsInnerFirstMessagesInner } from './ListBotsResponseBotsInnerFirstMessagesInner';
import { ListBotsResponseBotsInnerSafeguard } from './ListBotsResponseBotsInnerSafeguard';
import { HttpFile } from '../http/http';

export class ListBotsResponseBotsInner {
    'ai'?: ListBotsResponseBotsInnerAi;
    'bot'?: ListBotsResponseBotsInnerBot;
    'botCallbackUrl'?: string;
    'botStyle'?: ListBotsResponseBotsInnerBotStyle;
    'channelInvitationPreference'?: number;
    'createdAt'?: number;
    'enableMarkAsRead'?: boolean;
    'firstMessages'?: Array<ListBotsResponseBotsInnerFirstMessagesInner>;
    'isPrivacyMode'?: boolean;
    'safeguard'?: ListBotsResponseBotsInnerSafeguard;
    'showMember'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ai",
            "baseName": "ai",
            "type": "ListBotsResponseBotsInnerAi",
            "format": ""
        },
        {
            "name": "bot",
            "baseName": "bot",
            "type": "ListBotsResponseBotsInnerBot",
            "format": ""
        },
        {
            "name": "botCallbackUrl",
            "baseName": "bot_callback_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "botStyle",
            "baseName": "bot_style",
            "type": "ListBotsResponseBotsInnerBotStyle",
            "format": ""
        },
        {
            "name": "channelInvitationPreference",
            "baseName": "channel_invitation_preference",
            "type": "number",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "enableMarkAsRead",
            "baseName": "enable_mark_as_read",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "firstMessages",
            "baseName": "first_messages",
            "type": "Array<ListBotsResponseBotsInnerFirstMessagesInner>",
            "format": ""
        },
        {
            "name": "isPrivacyMode",
            "baseName": "is_privacy_mode",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "safeguard",
            "baseName": "safeguard",
            "type": "ListBotsResponseBotsInnerSafeguard",
            "format": ""
        },
        {
            "name": "showMember",
            "baseName": "show_member",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListBotsResponseBotsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

