/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListDataExportsByMessageChannelOrUserResponseExportedDataInnerFile } from './ListDataExportsByMessageChannelOrUserResponseExportedDataInnerFile';
import { HttpFile } from '../http/http';

export class ListDataExportsByMessageChannelOrUserResponseExportedDataInner {
    'requestId'?: string;
    'status'?: string;
    'format'?: string;
    'csvDelimiter'?: string;
    'timezone'?: string;
    'createdAt'?: number;
    'startTs'?: number;
    'endTs'?: number;
    'channelUrls'?: Array<string>;
    'senderIds'?: Array<string>;
    'file'?: ListDataExportsByMessageChannelOrUserResponseExportedDataInnerFile;
    'userIds'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "string",
            "format": ""
        },
        {
            "name": "csvDelimiter",
            "baseName": "csv_delimiter",
            "type": "string",
            "format": ""
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "number",
            "format": ""
        },
        {
            "name": "startTs",
            "baseName": "start_ts",
            "type": "number",
            "format": ""
        },
        {
            "name": "endTs",
            "baseName": "end_ts",
            "type": "number",
            "format": ""
        },
        {
            "name": "channelUrls",
            "baseName": "channel_urls",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "senderIds",
            "baseName": "sender_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "file",
            "baseName": "file",
            "type": "ListDataExportsByMessageChannelOrUserResponseExportedDataInnerFile",
            "format": ""
        },
        {
            "name": "userIds",
            "baseName": "user_ids",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListDataExportsByMessageChannelOrUserResponseExportedDataInner.attributeTypeMap;
    }

    public constructor() {
    }
}

