/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListDataExportsByMessageChannelOrUserResponseFile } from './ListDataExportsByMessageChannelOrUserResponseFile';
import { HttpFile } from '../http/http';

export class ListDataExportsByMessageChannelOrUserResponseExportedData {
    'requestId'?: string;
    'status'?: string;
    'format'?: string;
    'csvDelimiter'?: string;
    'timezone'?: string;
    'createdAt'?: number;
    'startTs'?: number;
    'endTs'?: number;
    'channelUrls'?: Array<string>;
    'senderIds'?: Array<string>;
    'file'?: ListDataExportsByMessageChannelOrUserResponseFile;
    'userIds'?: Array<number>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "string",
            "format": ""
        },
        {
            "name": "csvDelimiter",
            "baseName": "csv_delimiter",
            "type": "string",
            "format": ""
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "number",
            "format": ""
        },
        {
            "name": "startTs",
            "baseName": "start_ts",
            "type": "number",
            "format": ""
        },
        {
            "name": "endTs",
            "baseName": "end_ts",
            "type": "number",
            "format": ""
        },
        {
            "name": "channelUrls",
            "baseName": "channel_urls",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "senderIds",
            "baseName": "sender_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "file",
            "baseName": "file",
            "type": "ListDataExportsByMessageChannelOrUserResponseFile",
            "format": ""
        },
        {
            "name": "userIds",
            "baseName": "user_ids",
            "type": "Array<number>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListDataExportsByMessageChannelOrUserResponseExportedData.attributeTypeMap;
    }

    public constructor() {
    }
}

