/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MigrateMessagesAdminMessageRequest } from './MigrateMessagesAdminMessageRequest';
import { MigrateMessagesFileMessageRequest } from './MigrateMessagesFileMessageRequest';
import { MigrateMessagesFileMessageRequestThumbnailsInner } from './MigrateMessagesFileMessageRequestThumbnailsInner';
import { MigrateMessagesTextMessageRequest } from './MigrateMessagesTextMessageRequest';
import { HttpFile } from '../http/http';

export class MigrateMessagesRequestMessagesInner {
    'userId': string;
    'messageType': MigrateMessagesRequestMessagesInnerMessageTypeEnum;
    'message': string;
    'timestamp': number;
    'customType'?: string;
    'mentionedUserIds'?: Array<string>;
    'data'?: string;
    'dedupId'?: string;
    'sortedMetaarray'?: Array<any>;
    'url': string;
    'fileName'?: string;
    'fileSize'?: number;
    'fileType'?: string;
    'thumbnails'?: Array<MigrateMessagesFileMessageRequestThumbnailsInner>;
    'requireAuth'?: boolean;
    'customField'?: string;
    'isSilent'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "messageType",
            "baseName": "message_type",
            "type": "MigrateMessagesRequestMessagesInnerMessageTypeEnum",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "customType",
            "baseName": "custom_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "mentionedUserIds",
            "baseName": "mentioned_user_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "string",
            "format": ""
        },
        {
            "name": "dedupId",
            "baseName": "dedup_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "sortedMetaarray",
            "baseName": "sorted_metaarray",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileName",
            "baseName": "file_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileSize",
            "baseName": "file_size",
            "type": "number",
            "format": ""
        },
        {
            "name": "fileType",
            "baseName": "file_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "thumbnails",
            "baseName": "thumbnails",
            "type": "Array<MigrateMessagesFileMessageRequestThumbnailsInner>",
            "format": ""
        },
        {
            "name": "requireAuth",
            "baseName": "require_auth",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "customField",
            "baseName": "custom_field",
            "type": "string",
            "format": ""
        },
        {
            "name": "isSilent",
            "baseName": "is_silent",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MigrateMessagesRequestMessagesInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export type MigrateMessagesRequestMessagesInnerMessageTypeEnum = "ADMM" ;

