/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SendBirdOpenChannel } from './SendBirdOpenChannel';
import { HttpFile } from '../http/http';

export class OcListChannelsResponse {
    'channels'?: Array<SendBirdOpenChannel>;
    'next'?: string;
    'ts'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channels",
            "baseName": "channels",
            "type": "Array<SendBirdOpenChannel>",
            "format": ""
        },
        {
            "name": "next",
            "baseName": "next",
            "type": "string",
            "format": ""
        },
        {
            "name": "ts",
            "baseName": "ts",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OcListChannelsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

