/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ReportMessageByIdData {
    /**
    * Specifies the type of the channel. Either open_channels or group_channels.
    */
    'channelType': string;
    /**
    * Specifies the URL of the channel where the message to report is in.
    */
    'channelUrl': string;
    /**
    * Specifies the unique ID of the message to report.
    */
    'messageId': string;
    /**
    * Specifies the category which indicates the reason for reporting. Acceptable values are suspicious, harassing, inappropriate, and spam.
    */
    'reportCategory': string;
    /**
    * Specifies the unique ID of the user who has sent the message to report.
    */
    'offendingUserId': string;
    /**
    * Specifies the unique ID of the user who reports the message.
    */
    'reportingUserId': string;
    /**
    * Specifies additional information to be included in the report.
    */
    'reportDescription': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channelType",
            "baseName": "channel_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "channelUrl",
            "baseName": "channel_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "messageId",
            "baseName": "message_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "reportCategory",
            "baseName": "report_category",
            "type": "string",
            "format": ""
        },
        {
            "name": "offendingUserId",
            "baseName": "offending_user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "reportingUserId",
            "baseName": "reporting_user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "reportDescription",
            "baseName": "report_description",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReportMessageByIdData.attributeTypeMap;
    }

    public constructor() {
    }
}

