/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ScheduleAnAnnouncementRequestCreateChannelOptions } from './ScheduleAnAnnouncementRequestCreateChannelOptions';
import { ScheduleAnAnnouncementResponseMessage } from './ScheduleAnAnnouncementResponseMessage';
import { HttpFile } from '../http/http';

export class ScheduleAnAnnouncementResponse {
    'announcementGroup'?: string;
    'ceaseAt'?: string;
    'completedAt'?: number;
    'createChannel'?: boolean;
    'createChannelOptions'?: ScheduleAnAnnouncementRequestCreateChannelOptions;
    'enablePush'?: boolean;
    'endAt'?: number;
    'markAsRead'?: boolean;
    'message'?: ScheduleAnAnnouncementResponseMessage;
    'openCount'?: number;
    'openRate'?: number;
    'priority'?: string;
    'resumeAt'?: string;
    'scheduledAt'?: number;
    'sendToFrozenChannels'?: boolean;
    'sentChannelCount'?: number;
    'sentUserCount'?: number;
    'status'?: string;
    'targetAt'?: string;
    'targetChannelCount'?: number;
    'targetChannelType'?: string;
    'targetCustomType'?: string;
    'targetUserCount'?: number;
    'uniqueId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "announcementGroup",
            "baseName": "announcement_group",
            "type": "string",
            "format": ""
        },
        {
            "name": "ceaseAt",
            "baseName": "cease_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "completedAt",
            "baseName": "completed_at",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "createChannel",
            "baseName": "create_channel",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createChannelOptions",
            "baseName": "create_channel_options",
            "type": "ScheduleAnAnnouncementRequestCreateChannelOptions",
            "format": ""
        },
        {
            "name": "enablePush",
            "baseName": "enable_push",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "endAt",
            "baseName": "end_at",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "markAsRead",
            "baseName": "mark_as_read",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "ScheduleAnAnnouncementResponseMessage",
            "format": ""
        },
        {
            "name": "openCount",
            "baseName": "open_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "openRate",
            "baseName": "open_rate",
            "type": "number",
            "format": ""
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "string",
            "format": ""
        },
        {
            "name": "resumeAt",
            "baseName": "resume_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "scheduledAt",
            "baseName": "scheduled_at",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "sendToFrozenChannels",
            "baseName": "send_to_frozen_channels",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sentChannelCount",
            "baseName": "sent_channel_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "sentUserCount",
            "baseName": "sent_user_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "targetAt",
            "baseName": "target_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "targetChannelCount",
            "baseName": "target_channel_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "targetChannelType",
            "baseName": "target_channel_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "targetCustomType",
            "baseName": "target_custom_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "targetUserCount",
            "baseName": "target_user_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "uniqueId",
            "baseName": "unique_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ScheduleAnAnnouncementResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

