/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SendBirdMessageSendingStatus {
    'CANCELED'?: SendBirdMessageSendingStatusCANCELEDEnum;
    'FAILED'?: SendBirdMessageSendingStatusFAILEDEnum;
    'NONE'?: SendBirdMessageSendingStatusNONEEnum;
    'PENDING'?: SendBirdMessageSendingStatusPENDINGEnum;
    'SUCCEEDED'?: SendBirdMessageSendingStatusSUCCEEDEDEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "CANCELED",
            "baseName": "CANCELED",
            "type": "SendBirdMessageSendingStatusCANCELEDEnum",
            "format": ""
        },
        {
            "name": "FAILED",
            "baseName": "FAILED",
            "type": "SendBirdMessageSendingStatusFAILEDEnum",
            "format": ""
        },
        {
            "name": "NONE",
            "baseName": "NONE",
            "type": "SendBirdMessageSendingStatusNONEEnum",
            "format": ""
        },
        {
            "name": "PENDING",
            "baseName": "PENDING",
            "type": "SendBirdMessageSendingStatusPENDINGEnum",
            "format": ""
        },
        {
            "name": "SUCCEEDED",
            "baseName": "SUCCEEDED",
            "type": "SendBirdMessageSendingStatusSUCCEEDEDEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdMessageSendingStatus.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SendBirdMessageSendingStatusCANCELEDEnum = "canceled" ;
export type SendBirdMessageSendingStatusFAILEDEnum = "failed" ;
export type SendBirdMessageSendingStatusNONEEnum = "none" ;
export type SendBirdMessageSendingStatusPENDINGEnum = "pending" ;
export type SendBirdMessageSendingStatusSUCCEEDEDEnum = "succeeded" ;

