/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SendBirdGroupChannelFilterStaticHiddenChannelFilter {
    'HIDDEN'?: SendBirdGroupChannelFilterStaticHiddenChannelFilterHIDDENEnum;
    'HIDDEN_ALLOW_AUTO_UNHIDE'?: SendBirdGroupChannelFilterStaticHiddenChannelFilterHIDDENALLOWAUTOUNHIDEEnum;
    'HIDDEN_PREVENT_AUTO_UNHIDE'?: SendBirdGroupChannelFilterStaticHiddenChannelFilterHIDDENPREVENTAUTOUNHIDEEnum;
    'UNHIDDEN'?: SendBirdGroupChannelFilterStaticHiddenChannelFilterUNHIDDENEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "HIDDEN",
            "baseName": "HIDDEN",
            "type": "SendBirdGroupChannelFilterStaticHiddenChannelFilterHIDDENEnum",
            "format": ""
        },
        {
            "name": "HIDDEN_ALLOW_AUTO_UNHIDE",
            "baseName": "HIDDEN_ALLOW_AUTO_UNHIDE",
            "type": "SendBirdGroupChannelFilterStaticHiddenChannelFilterHIDDENALLOWAUTOUNHIDEEnum",
            "format": ""
        },
        {
            "name": "HIDDEN_PREVENT_AUTO_UNHIDE",
            "baseName": "HIDDEN_PREVENT_AUTO_UNHIDE",
            "type": "SendBirdGroupChannelFilterStaticHiddenChannelFilterHIDDENPREVENTAUTOUNHIDEEnum",
            "format": ""
        },
        {
            "name": "UNHIDDEN",
            "baseName": "UNHIDDEN",
            "type": "SendBirdGroupChannelFilterStaticHiddenChannelFilterUNHIDDENEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdGroupChannelFilterStaticHiddenChannelFilter.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SendBirdGroupChannelFilterStaticHiddenChannelFilterHIDDENEnum = "hidden_only" ;
export type SendBirdGroupChannelFilterStaticHiddenChannelFilterHIDDENALLOWAUTOUNHIDEEnum = "hidden_allow_auto_unhide" ;
export type SendBirdGroupChannelFilterStaticHiddenChannelFilterHIDDENPREVENTAUTOUNHIDEEnum = "hidden_prevent_auto_unhide" ;
export type SendBirdGroupChannelFilterStaticHiddenChannelFilterUNHIDDENEnum = "unhidden_only" ;

