/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SendBirdGroupChannelFilterStaticSearchField {
    'CHANNEL_NAME'?: SendBirdGroupChannelFilterStaticSearchFieldCHANNELNAMEEnum;
    'MEMBER_NICKNAME'?: SendBirdGroupChannelFilterStaticSearchFieldMEMBERNICKNAMEEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "CHANNEL_NAME",
            "baseName": "CHANNEL_NAME",
            "type": "SendBirdGroupChannelFilterStaticSearchFieldCHANNELNAMEEnum",
            "format": ""
        },
        {
            "name": "MEMBER_NICKNAME",
            "baseName": "MEMBER_NICKNAME",
            "type": "SendBirdGroupChannelFilterStaticSearchFieldMEMBERNICKNAMEEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdGroupChannelFilterStaticSearchField.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SendBirdGroupChannelFilterStaticSearchFieldCHANNELNAMEEnum = "channel_name" ;
export type SendBirdGroupChannelFilterStaticSearchFieldMEMBERNICKNAMEEnum = "member_nickname" ;

