/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SendBirdPublicGroupChannelListQuery {
    'channelNameContainsFilter'?: string;
    'channelUrlsFilter'?: Array<string>;
    'customTypeStartsWithFilter'?: string;
    'customTypesFilter'?: Array<string>;
    'hasNext'?: boolean;
    'includeEmpty'?: boolean;
    'includeFrozen'?: boolean;
    'isLoading'?: boolean;
    'limit'?: number;
    'membershipFilter'?: SendBirdPublicGroupChannelListQueryMembershipFilterEnum;
    'metadataKey'?: string;
    'metadataOrderKeyFilter'?: string;
    'metadataValueStartsWith'?: string;
    'metadataValues'?: Array<string>;
    'order'?: SendBirdPublicGroupChannelListQueryOrderEnum;
    'superChannelFilter'?: SendBirdPublicGroupChannelListQuerySuperChannelFilterEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channelNameContainsFilter",
            "baseName": "channelNameContainsFilter",
            "type": "string",
            "format": ""
        },
        {
            "name": "channelUrlsFilter",
            "baseName": "channelUrlsFilter",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "customTypeStartsWithFilter",
            "baseName": "customTypeStartsWithFilter",
            "type": "string",
            "format": ""
        },
        {
            "name": "customTypesFilter",
            "baseName": "customTypesFilter",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "hasNext",
            "baseName": "hasNext",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "includeEmpty",
            "baseName": "includeEmpty",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "includeFrozen",
            "baseName": "includeFrozen",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isLoading",
            "baseName": "isLoading",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": ""
        },
        {
            "name": "membershipFilter",
            "baseName": "membershipFilter",
            "type": "SendBirdPublicGroupChannelListQueryMembershipFilterEnum",
            "format": ""
        },
        {
            "name": "metadataKey",
            "baseName": "metadataKey",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadataOrderKeyFilter",
            "baseName": "metadataOrderKeyFilter",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadataValueStartsWith",
            "baseName": "metadataValueStartsWith",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadataValues",
            "baseName": "metadataValues",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "SendBirdPublicGroupChannelListQueryOrderEnum",
            "format": ""
        },
        {
            "name": "superChannelFilter",
            "baseName": "superChannelFilter",
            "type": "SendBirdPublicGroupChannelListQuerySuperChannelFilterEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdPublicGroupChannelListQuery.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SendBirdPublicGroupChannelListQueryMembershipFilterEnum = "all" | "joined" ;
export type SendBirdPublicGroupChannelListQueryOrderEnum = "channel_name_alphabetical" | "chronological" | "metadata_value_alphabetical" ;
export type SendBirdPublicGroupChannelListQuerySuperChannelFilterEnum = "all" | "broadcast_only" | "nonsuper" | "super" ;

