/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SendBirdLogLevel {
    'DEBUG'?: SendBirdLogLevelDEBUGEnum;
    'ERROR'?: SendBirdLogLevelERROREnum;
    'INFO'?: SendBirdLogLevelINFOEnum;
    'NONE'?: SendBirdLogLevelNONEEnum;
    'VERBOSE'?: SendBirdLogLevelVERBOSEEnum;
    'WARN'?: SendBirdLogLevelWARNEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "DEBUG",
            "baseName": "DEBUG",
            "type": "SendBirdLogLevelDEBUGEnum",
            "format": ""
        },
        {
            "name": "ERROR",
            "baseName": "ERROR",
            "type": "SendBirdLogLevelERROREnum",
            "format": ""
        },
        {
            "name": "INFO",
            "baseName": "INFO",
            "type": "SendBirdLogLevelINFOEnum",
            "format": ""
        },
        {
            "name": "NONE",
            "baseName": "NONE",
            "type": "SendBirdLogLevelNONEEnum",
            "format": ""
        },
        {
            "name": "VERBOSE",
            "baseName": "VERBOSE",
            "type": "SendBirdLogLevelVERBOSEEnum",
            "format": ""
        },
        {
            "name": "WARN",
            "baseName": "WARN",
            "type": "SendBirdLogLevelWARNEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdLogLevel.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SendBirdLogLevelDEBUGEnum = "debug" ;
export type SendBirdLogLevelERROREnum = "error" ;
export type SendBirdLogLevelINFOEnum = "info" ;
export type SendBirdLogLevelNONEEnum = "none" ;
export type SendBirdLogLevelVERBOSEEnum = "verbose" ;
export type SendBirdLogLevelWARNEnum = "warn" ;

