/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SendBirdGroupChannelCollectionStaticGroupChannelOrder {
    'CHANNEL_NAME_ALPHABETICAL'?: SendBirdGroupChannelCollectionStaticGroupChannelOrderCHANNELNAMEALPHABETICALEnum;
    'CHRONOLOGICAL'?: SendBirdGroupChannelCollectionStaticGroupChannelOrderCHRONOLOGICALEnum;
    'LATEST_LAST_MESSAGE'?: SendBirdGroupChannelCollectionStaticGroupChannelOrderLATESTLASTMESSAGEEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "CHANNEL_NAME_ALPHABETICAL",
            "baseName": "CHANNEL_NAME_ALPHABETICAL",
            "type": "SendBirdGroupChannelCollectionStaticGroupChannelOrderCHANNELNAMEALPHABETICALEnum",
            "format": ""
        },
        {
            "name": "CHRONOLOGICAL",
            "baseName": "CHRONOLOGICAL",
            "type": "SendBirdGroupChannelCollectionStaticGroupChannelOrderCHRONOLOGICALEnum",
            "format": ""
        },
        {
            "name": "LATEST_LAST_MESSAGE",
            "baseName": "LATEST_LAST_MESSAGE",
            "type": "SendBirdGroupChannelCollectionStaticGroupChannelOrderLATESTLASTMESSAGEEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdGroupChannelCollectionStaticGroupChannelOrder.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SendBirdGroupChannelCollectionStaticGroupChannelOrderCHANNELNAMEALPHABETICALEnum = "channel_name_alphabetical" ;
export type SendBirdGroupChannelCollectionStaticGroupChannelOrderCHRONOLOGICALEnum = "chronological" ;
export type SendBirdGroupChannelCollectionStaticGroupChannelOrderLATESTLASTMESSAGEEnum = "latest_last_message" ;

