/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SendBirdSuperChannelFilter {
    'ALL'?: SendBirdSuperChannelFilterALLEnum;
    'NON_SUPER'?: SendBirdSuperChannelFilterNONSUPEREnum;
    'SUPER'?: SendBirdSuperChannelFilterSUPEREnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ALL",
            "baseName": "ALL",
            "type": "SendBirdSuperChannelFilterALLEnum",
            "format": ""
        },
        {
            "name": "NON_SUPER",
            "baseName": "NON_SUPER",
            "type": "SendBirdSuperChannelFilterNONSUPEREnum",
            "format": ""
        },
        {
            "name": "SUPER",
            "baseName": "SUPER",
            "type": "SendBirdSuperChannelFilterSUPEREnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdSuperChannelFilter.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SendBirdSuperChannelFilterALLEnum = "all" ;
export type SendBirdSuperChannelFilterNONSUPEREnum = "nonsuper" ;
export type SendBirdSuperChannelFilterSUPEREnum = "super" ;

