/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SendBirdMessageSearchQueryOptions {
    'advancedQuery'?: boolean;
    'channelCustomType'?: string;
    'channelUrl'?: string;
    'exactMatch'?: boolean;
    'limit'?: number;
    'messageTimestampFrom'?: number;
    'messageTimestampTo'?: number;
    'order'?: SendBirdMessageSearchQueryOptionsOrderEnum;
    'reverse'?: boolean;
    'targetFields'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "advancedQuery",
            "baseName": "advancedQuery",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "channelCustomType",
            "baseName": "channelCustomType",
            "type": "string",
            "format": ""
        },
        {
            "name": "channelUrl",
            "baseName": "channelUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "exactMatch",
            "baseName": "exactMatch",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": ""
        },
        {
            "name": "messageTimestampFrom",
            "baseName": "messageTimestampFrom",
            "type": "number",
            "format": ""
        },
        {
            "name": "messageTimestampTo",
            "baseName": "messageTimestampTo",
            "type": "number",
            "format": ""
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "SendBirdMessageSearchQueryOptionsOrderEnum",
            "format": ""
        },
        {
            "name": "reverse",
            "baseName": "reverse",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "targetFields",
            "baseName": "targetFields",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdMessageSearchQueryOptions.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SendBirdMessageSearchQueryOptionsOrderEnum = "score" | "ts" ;

