/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SendBirdAppleCriticalAlertOptions } from './SendBirdAppleCriticalAlertOptions';
import { SendBirdMessageMetaArray } from './SendBirdMessageMetaArray';
import { SendBirdUser } from './SendBirdUser';
import { HttpFile } from '../http/http';

export class SendBirdBaseMessageParams {
    'appleCriticalAlertOptions'?: SendBirdAppleCriticalAlertOptions;
    'customType'?: string;
    'data'?: string;
    'isReplyToChannel'?: boolean;
    'mentionType'?: SendBirdBaseMessageParamsMentionTypeEnum;
    'mentionedUserIds'?: Array<string>;
    'mentionedUsers'?: Array<SendBirdUser>;
    'metaArrayKeys'?: Array<string>;
    'metaArrays'?: Array<SendBirdMessageMetaArray>;
    'parentMessageId'?: number;
    'pushNotificationDeliveryOption'?: SendBirdBaseMessageParamsPushNotificationDeliveryOptionEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "appleCriticalAlertOptions",
            "baseName": "appleCriticalAlertOptions",
            "type": "SendBirdAppleCriticalAlertOptions",
            "format": ""
        },
        {
            "name": "customType",
            "baseName": "customType",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "string",
            "format": ""
        },
        {
            "name": "isReplyToChannel",
            "baseName": "isReplyToChannel",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "mentionType",
            "baseName": "mentionType",
            "type": "SendBirdBaseMessageParamsMentionTypeEnum",
            "format": ""
        },
        {
            "name": "mentionedUserIds",
            "baseName": "mentionedUserIds",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "mentionedUsers",
            "baseName": "mentionedUsers",
            "type": "Array<SendBirdUser>",
            "format": ""
        },
        {
            "name": "metaArrayKeys",
            "baseName": "metaArrayKeys",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "metaArrays",
            "baseName": "metaArrays",
            "type": "Array<SendBirdMessageMetaArray>",
            "format": ""
        },
        {
            "name": "parentMessageId",
            "baseName": "parentMessageId",
            "type": "number",
            "format": ""
        },
        {
            "name": "pushNotificationDeliveryOption",
            "baseName": "pushNotificationDeliveryOption",
            "type": "SendBirdBaseMessageParamsPushNotificationDeliveryOptionEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdBaseMessageParams.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SendBirdBaseMessageParamsMentionTypeEnum = "channel" | "users" ;
export type SendBirdBaseMessageParamsPushNotificationDeliveryOptionEnum = "default" | "suppress" ;

