/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelObject } from './ModelObject';
import { HttpFile } from '../http/http';

/**
* User
*/
export class SendBirdUser {
    'connectionStatus'?: string;
    'friendDiscoveryKey'?: string;
    'friendName'?: string;
    'isActive'?: boolean;
    'lastSeenAt'?: string;
    'metaData'?: ModelObject;
    'nickname'?: string;
    'plainProfileUrl'?: string;
    'preferredLanguages'?: Array<string>;
    'profileUrl'?: string;
    'requireAuth'?: boolean;
    'userId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "connectionStatus",
            "baseName": "connection_status",
            "type": "string",
            "format": ""
        },
        {
            "name": "friendDiscoveryKey",
            "baseName": "friend_discovery_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "friendName",
            "baseName": "friend_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "isActive",
            "baseName": "is_active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "lastSeenAt",
            "baseName": "last_seen_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "metaData",
            "baseName": "meta_data",
            "type": "ModelObject",
            "format": ""
        },
        {
            "name": "nickname",
            "baseName": "nickname",
            "type": "string",
            "format": ""
        },
        {
            "name": "plainProfileUrl",
            "baseName": "plain_profile_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "preferredLanguages",
            "baseName": "preferred_languages",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "profileUrl",
            "baseName": "profile_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "requireAuth",
            "baseName": "require_auth",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdUser.attributeTypeMap;
    }

    public constructor() {
    }
}

