/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SendBirdGroupChannelContextSource {
    'CHANNEL_BACKGROUND'?: SendBirdGroupChannelContextSourceCHANNELBACKGROUNDEnum;
    'CHANNEL_CHANGELOG'?: SendBirdGroupChannelContextSourceCHANNELCHANGELOGEnum;
    'EVENT_CHANNEL_CHANGED'?: SendBirdGroupChannelContextSourceEVENTCHANNELCHANGEDEnum;
    'EVENT_CHANNEL_DELETED'?: SendBirdGroupChannelContextSourceEVENTCHANNELDELETEDEnum;
    'EVENT_CHANNEL_ENTER'?: SendBirdGroupChannelContextSourceEVENTCHANNELENTEREnum;
    'EVENT_CHANNEL_EXIT'?: SendBirdGroupChannelContextSourceEVENTCHANNELEXITEnum;
    'EVENT_CHANNEL_FROZEN'?: SendBirdGroupChannelContextSourceEVENTCHANNELFROZENEnum;
    'EVENT_CHANNEL_HIDDEN'?: SendBirdGroupChannelContextSourceEVENTCHANNELHIDDENEnum;
    'EVENT_CHANNEL_METACOUNTER_DELETED'?: SendBirdGroupChannelContextSourceEVENTCHANNELMETACOUNTERDELETEDEnum;
    'EVENT_CHANNEL_METACOUNTER_UPDATED'?: SendBirdGroupChannelContextSourceEVENTCHANNELMETACOUNTERUPDATEDEnum;
    'EVENT_CHANNEL_METADATA_DELETED'?: SendBirdGroupChannelContextSourceEVENTCHANNELMETADATADELETEDEnum;
    'EVENT_CHANNEL_METADATA_UPDATED'?: SendBirdGroupChannelContextSourceEVENTCHANNELMETADATAUPDATEDEnum;
    'EVENT_CHANNEL_UNFROZEN'?: SendBirdGroupChannelContextSourceEVENTCHANNELUNFROZENEnum;
    'EVENT_CHANNEL_UNHIDDEN'?: SendBirdGroupChannelContextSourceEVENTCHANNELUNHIDDENEnum;
    'EVENT_DELIVERY_RECEIPT_UPDATED'?: SendBirdGroupChannelContextSourceEVENTDELIVERYRECEIPTUPDATEDEnum;
    'EVENT_MENTION'?: SendBirdGroupChannelContextSourceEVENTMENTIONEnum;
    'EVENT_MESSAGE_DELETED'?: SendBirdGroupChannelContextSourceEVENTMESSAGEDELETEDEnum;
    'EVENT_MESSAGE_RECEIVED'?: SendBirdGroupChannelContextSourceEVENTMESSAGERECEIVEDEnum;
    'EVENT_MESSAGE_SENT'?: SendBirdGroupChannelContextSourceEVENTMESSAGESENTEnum;
    'EVENT_MESSAGE_UPDATED'?: SendBirdGroupChannelContextSourceEVENTMESSAGEUPDATEDEnum;
    'EVENT_OPERATOR_UPDATED'?: SendBirdGroupChannelContextSourceEVENTOPERATORUPDATEDEnum;
    'EVENT_REACTION_UPDATED'?: SendBirdGroupChannelContextSourceEVENTREACTIONUPDATEDEnum;
    'EVENT_READ_RECEIPT_UPDATED'?: SendBirdGroupChannelContextSourceEVENTREADRECEIPTUPDATEDEnum;
    'EVENT_THREAD_INFO_UPDATED'?: SendBirdGroupChannelContextSourceEVENTTHREADINFOUPDATEDEnum;
    'EVENT_TYPING_STATUS_UPDATED'?: SendBirdGroupChannelContextSourceEVENTTYPINGSTATUSUPDATEDEnum;
    'EVENT_USER_BANNED'?: SendBirdGroupChannelContextSourceEVENTUSERBANNEDEnum;
    'EVENT_USER_DECLINED_INVITATION'?: SendBirdGroupChannelContextSourceEVENTUSERDECLINEDINVITATIONEnum;
    'EVENT_USER_JOINED'?: SendBirdGroupChannelContextSourceEVENTUSERJOINEDEnum;
    'EVENT_USER_LEFT'?: SendBirdGroupChannelContextSourceEVENTUSERLEFTEnum;
    'EVENT_USER_MUTED'?: SendBirdGroupChannelContextSourceEVENTUSERMUTEDEnum;
    'EVENT_USER_RECEIVED_INVITATION'?: SendBirdGroupChannelContextSourceEVENTUSERRECEIVEDINVITATIONEnum;
    'EVENT_USER_UNBANNED'?: SendBirdGroupChannelContextSourceEVENTUSERUNBANNEDEnum;
    'EVENT_USER_UNMUTED'?: SendBirdGroupChannelContextSourceEVENTUSERUNMUTEDEnum;
    'LOCAL_MESSAGE_CANCELED'?: SendBirdGroupChannelContextSourceLOCALMESSAGECANCELEDEnum;
    'LOCAL_MESSAGE_FAILED'?: SendBirdGroupChannelContextSourceLOCALMESSAGEFAILEDEnum;
    'LOCAL_MESSAGE_PENDING_CREATED'?: SendBirdGroupChannelContextSourceLOCALMESSAGEPENDINGCREATEDEnum;
    'LOCAL_MESSAGE_RESEND_STARTED'?: SendBirdGroupChannelContextSourceLOCALMESSAGERESENDSTARTEDEnum;
    'MESSAGE_BACKGROUND'?: SendBirdGroupChannelContextSourceMESSAGEBACKGROUNDEnum;
    'MESSAGE_CHANGELOG'?: SendBirdGroupChannelContextSourceMESSAGECHANGELOGEnum;
    'MESSAGE_COLLECTION_FILTER_MISMATCH'?: SendBirdGroupChannelContextSourceMESSAGECOLLECTIONFILTERMISMATCHEnum;
    'MESSAGE_FILL'?: SendBirdGroupChannelContextSourceMESSAGEFILLEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "CHANNEL_BACKGROUND",
            "baseName": "CHANNEL_BACKGROUND",
            "type": "SendBirdGroupChannelContextSourceCHANNELBACKGROUNDEnum",
            "format": ""
        },
        {
            "name": "CHANNEL_CHANGELOG",
            "baseName": "CHANNEL_CHANGELOG",
            "type": "SendBirdGroupChannelContextSourceCHANNELCHANGELOGEnum",
            "format": ""
        },
        {
            "name": "EVENT_CHANNEL_CHANGED",
            "baseName": "EVENT_CHANNEL_CHANGED",
            "type": "SendBirdGroupChannelContextSourceEVENTCHANNELCHANGEDEnum",
            "format": ""
        },
        {
            "name": "EVENT_CHANNEL_DELETED",
            "baseName": "EVENT_CHANNEL_DELETED",
            "type": "SendBirdGroupChannelContextSourceEVENTCHANNELDELETEDEnum",
            "format": ""
        },
        {
            "name": "EVENT_CHANNEL_ENTER",
            "baseName": "EVENT_CHANNEL_ENTER",
            "type": "SendBirdGroupChannelContextSourceEVENTCHANNELENTEREnum",
            "format": ""
        },
        {
            "name": "EVENT_CHANNEL_EXIT",
            "baseName": "EVENT_CHANNEL_EXIT",
            "type": "SendBirdGroupChannelContextSourceEVENTCHANNELEXITEnum",
            "format": ""
        },
        {
            "name": "EVENT_CHANNEL_FROZEN",
            "baseName": "EVENT_CHANNEL_FROZEN",
            "type": "SendBirdGroupChannelContextSourceEVENTCHANNELFROZENEnum",
            "format": ""
        },
        {
            "name": "EVENT_CHANNEL_HIDDEN",
            "baseName": "EVENT_CHANNEL_HIDDEN",
            "type": "SendBirdGroupChannelContextSourceEVENTCHANNELHIDDENEnum",
            "format": ""
        },
        {
            "name": "EVENT_CHANNEL_METACOUNTER_DELETED",
            "baseName": "EVENT_CHANNEL_METACOUNTER_DELETED",
            "type": "SendBirdGroupChannelContextSourceEVENTCHANNELMETACOUNTERDELETEDEnum",
            "format": ""
        },
        {
            "name": "EVENT_CHANNEL_METACOUNTER_UPDATED",
            "baseName": "EVENT_CHANNEL_METACOUNTER_UPDATED",
            "type": "SendBirdGroupChannelContextSourceEVENTCHANNELMETACOUNTERUPDATEDEnum",
            "format": ""
        },
        {
            "name": "EVENT_CHANNEL_METADATA_DELETED",
            "baseName": "EVENT_CHANNEL_METADATA_DELETED",
            "type": "SendBirdGroupChannelContextSourceEVENTCHANNELMETADATADELETEDEnum",
            "format": ""
        },
        {
            "name": "EVENT_CHANNEL_METADATA_UPDATED",
            "baseName": "EVENT_CHANNEL_METADATA_UPDATED",
            "type": "SendBirdGroupChannelContextSourceEVENTCHANNELMETADATAUPDATEDEnum",
            "format": ""
        },
        {
            "name": "EVENT_CHANNEL_UNFROZEN",
            "baseName": "EVENT_CHANNEL_UNFROZEN",
            "type": "SendBirdGroupChannelContextSourceEVENTCHANNELUNFROZENEnum",
            "format": ""
        },
        {
            "name": "EVENT_CHANNEL_UNHIDDEN",
            "baseName": "EVENT_CHANNEL_UNHIDDEN",
            "type": "SendBirdGroupChannelContextSourceEVENTCHANNELUNHIDDENEnum",
            "format": ""
        },
        {
            "name": "EVENT_DELIVERY_RECEIPT_UPDATED",
            "baseName": "EVENT_DELIVERY_RECEIPT_UPDATED",
            "type": "SendBirdGroupChannelContextSourceEVENTDELIVERYRECEIPTUPDATEDEnum",
            "format": ""
        },
        {
            "name": "EVENT_MENTION",
            "baseName": "EVENT_MENTION",
            "type": "SendBirdGroupChannelContextSourceEVENTMENTIONEnum",
            "format": ""
        },
        {
            "name": "EVENT_MESSAGE_DELETED",
            "baseName": "EVENT_MESSAGE_DELETED",
            "type": "SendBirdGroupChannelContextSourceEVENTMESSAGEDELETEDEnum",
            "format": ""
        },
        {
            "name": "EVENT_MESSAGE_RECEIVED",
            "baseName": "EVENT_MESSAGE_RECEIVED",
            "type": "SendBirdGroupChannelContextSourceEVENTMESSAGERECEIVEDEnum",
            "format": ""
        },
        {
            "name": "EVENT_MESSAGE_SENT",
            "baseName": "EVENT_MESSAGE_SENT",
            "type": "SendBirdGroupChannelContextSourceEVENTMESSAGESENTEnum",
            "format": ""
        },
        {
            "name": "EVENT_MESSAGE_UPDATED",
            "baseName": "EVENT_MESSAGE_UPDATED",
            "type": "SendBirdGroupChannelContextSourceEVENTMESSAGEUPDATEDEnum",
            "format": ""
        },
        {
            "name": "EVENT_OPERATOR_UPDATED",
            "baseName": "EVENT_OPERATOR_UPDATED",
            "type": "SendBirdGroupChannelContextSourceEVENTOPERATORUPDATEDEnum",
            "format": ""
        },
        {
            "name": "EVENT_REACTION_UPDATED",
            "baseName": "EVENT_REACTION_UPDATED",
            "type": "SendBirdGroupChannelContextSourceEVENTREACTIONUPDATEDEnum",
            "format": ""
        },
        {
            "name": "EVENT_READ_RECEIPT_UPDATED",
            "baseName": "EVENT_READ_RECEIPT_UPDATED",
            "type": "SendBirdGroupChannelContextSourceEVENTREADRECEIPTUPDATEDEnum",
            "format": ""
        },
        {
            "name": "EVENT_THREAD_INFO_UPDATED",
            "baseName": "EVENT_THREAD_INFO_UPDATED",
            "type": "SendBirdGroupChannelContextSourceEVENTTHREADINFOUPDATEDEnum",
            "format": ""
        },
        {
            "name": "EVENT_TYPING_STATUS_UPDATED",
            "baseName": "EVENT_TYPING_STATUS_UPDATED",
            "type": "SendBirdGroupChannelContextSourceEVENTTYPINGSTATUSUPDATEDEnum",
            "format": ""
        },
        {
            "name": "EVENT_USER_BANNED",
            "baseName": "EVENT_USER_BANNED",
            "type": "SendBirdGroupChannelContextSourceEVENTUSERBANNEDEnum",
            "format": ""
        },
        {
            "name": "EVENT_USER_DECLINED_INVITATION",
            "baseName": "EVENT_USER_DECLINED_INVITATION",
            "type": "SendBirdGroupChannelContextSourceEVENTUSERDECLINEDINVITATIONEnum",
            "format": ""
        },
        {
            "name": "EVENT_USER_JOINED",
            "baseName": "EVENT_USER_JOINED",
            "type": "SendBirdGroupChannelContextSourceEVENTUSERJOINEDEnum",
            "format": ""
        },
        {
            "name": "EVENT_USER_LEFT",
            "baseName": "EVENT_USER_LEFT",
            "type": "SendBirdGroupChannelContextSourceEVENTUSERLEFTEnum",
            "format": ""
        },
        {
            "name": "EVENT_USER_MUTED",
            "baseName": "EVENT_USER_MUTED",
            "type": "SendBirdGroupChannelContextSourceEVENTUSERMUTEDEnum",
            "format": ""
        },
        {
            "name": "EVENT_USER_RECEIVED_INVITATION",
            "baseName": "EVENT_USER_RECEIVED_INVITATION",
            "type": "SendBirdGroupChannelContextSourceEVENTUSERRECEIVEDINVITATIONEnum",
            "format": ""
        },
        {
            "name": "EVENT_USER_UNBANNED",
            "baseName": "EVENT_USER_UNBANNED",
            "type": "SendBirdGroupChannelContextSourceEVENTUSERUNBANNEDEnum",
            "format": ""
        },
        {
            "name": "EVENT_USER_UNMUTED",
            "baseName": "EVENT_USER_UNMUTED",
            "type": "SendBirdGroupChannelContextSourceEVENTUSERUNMUTEDEnum",
            "format": ""
        },
        {
            "name": "LOCAL_MESSAGE_CANCELED",
            "baseName": "LOCAL_MESSAGE_CANCELED",
            "type": "SendBirdGroupChannelContextSourceLOCALMESSAGECANCELEDEnum",
            "format": ""
        },
        {
            "name": "LOCAL_MESSAGE_FAILED",
            "baseName": "LOCAL_MESSAGE_FAILED",
            "type": "SendBirdGroupChannelContextSourceLOCALMESSAGEFAILEDEnum",
            "format": ""
        },
        {
            "name": "LOCAL_MESSAGE_PENDING_CREATED",
            "baseName": "LOCAL_MESSAGE_PENDING_CREATED",
            "type": "SendBirdGroupChannelContextSourceLOCALMESSAGEPENDINGCREATEDEnum",
            "format": ""
        },
        {
            "name": "LOCAL_MESSAGE_RESEND_STARTED",
            "baseName": "LOCAL_MESSAGE_RESEND_STARTED",
            "type": "SendBirdGroupChannelContextSourceLOCALMESSAGERESENDSTARTEDEnum",
            "format": ""
        },
        {
            "name": "MESSAGE_BACKGROUND",
            "baseName": "MESSAGE_BACKGROUND",
            "type": "SendBirdGroupChannelContextSourceMESSAGEBACKGROUNDEnum",
            "format": ""
        },
        {
            "name": "MESSAGE_CHANGELOG",
            "baseName": "MESSAGE_CHANGELOG",
            "type": "SendBirdGroupChannelContextSourceMESSAGECHANGELOGEnum",
            "format": ""
        },
        {
            "name": "MESSAGE_COLLECTION_FILTER_MISMATCH",
            "baseName": "MESSAGE_COLLECTION_FILTER_MISMATCH",
            "type": "SendBirdGroupChannelContextSourceMESSAGECOLLECTIONFILTERMISMATCHEnum",
            "format": ""
        },
        {
            "name": "MESSAGE_FILL",
            "baseName": "MESSAGE_FILL",
            "type": "SendBirdGroupChannelContextSourceMESSAGEFILLEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdGroupChannelContextSource.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SendBirdGroupChannelContextSourceCHANNELBACKGROUNDEnum = "1000" ;
export type SendBirdGroupChannelContextSourceCHANNELCHANGELOGEnum = "1001" ;
export type SendBirdGroupChannelContextSourceEVENTCHANNELCHANGEDEnum = "0" ;
export type SendBirdGroupChannelContextSourceEVENTCHANNELDELETEDEnum = "17" ;
export type SendBirdGroupChannelContextSourceEVENTCHANNELENTEREnum = "5" ;
export type SendBirdGroupChannelContextSourceEVENTCHANNELEXITEnum = "6" ;
export type SendBirdGroupChannelContextSourceEVENTCHANNELFROZENEnum = "7" ;
export type SendBirdGroupChannelContextSourceEVENTCHANNELHIDDENEnum = "9" ;
export type SendBirdGroupChannelContextSourceEVENTCHANNELMETACOUNTERDELETEDEnum = "16" ;
export type SendBirdGroupChannelContextSourceEVENTCHANNELMETACOUNTERUPDATEDEnum = "15" ;
export type SendBirdGroupChannelContextSourceEVENTCHANNELMETADATADELETEDEnum = "14" ;
export type SendBirdGroupChannelContextSourceEVENTCHANNELMETADATAUPDATEDEnum = "13" ;
export type SendBirdGroupChannelContextSourceEVENTCHANNELUNFROZENEnum = "8" ;
export type SendBirdGroupChannelContextSourceEVENTCHANNELUNHIDDENEnum = "10" ;
export type SendBirdGroupChannelContextSourceEVENTDELIVERYRECEIPTUPDATEDEnum = "27" ;
export type SendBirdGroupChannelContextSourceEVENTMENTIONEnum = "28" ;
export type SendBirdGroupChannelContextSourceEVENTMESSAGEDELETEDEnum = "25" ;
export type SendBirdGroupChannelContextSourceEVENTMESSAGERECEIVEDEnum = "22" ;
export type SendBirdGroupChannelContextSourceEVENTMESSAGESENTEnum = "23" ;
export type SendBirdGroupChannelContextSourceEVENTMESSAGEUPDATEDEnum = "24" ;
export type SendBirdGroupChannelContextSourceEVENTOPERATORUPDATEDEnum = "12" ;
export type SendBirdGroupChannelContextSourceEVENTREACTIONUPDATEDEnum = "29" ;
export type SendBirdGroupChannelContextSourceEVENTREADRECEIPTUPDATEDEnum = "26" ;
export type SendBirdGroupChannelContextSourceEVENTTHREADINFOUPDATEDEnum = "30" ;
export type SendBirdGroupChannelContextSourceEVENTTYPINGSTATUSUPDATEDEnum = "11" ;
export type SendBirdGroupChannelContextSourceEVENTUSERBANNEDEnum = "20" ;
export type SendBirdGroupChannelContextSourceEVENTUSERDECLINEDINVITATIONEnum = "2" ;
export type SendBirdGroupChannelContextSourceEVENTUSERJOINEDEnum = "3" ;
export type SendBirdGroupChannelContextSourceEVENTUSERLEFTEnum = "4" ;
export type SendBirdGroupChannelContextSourceEVENTUSERMUTEDEnum = "18" ;
export type SendBirdGroupChannelContextSourceEVENTUSERRECEIVEDINVITATIONEnum = "1" ;
export type SendBirdGroupChannelContextSourceEVENTUSERUNBANNEDEnum = "21" ;
export type SendBirdGroupChannelContextSourceEVENTUSERUNMUTEDEnum = "19" ;
export type SendBirdGroupChannelContextSourceLOCALMESSAGECANCELEDEnum = "2002" ;
export type SendBirdGroupChannelContextSourceLOCALMESSAGEFAILEDEnum = "2001" ;
export type SendBirdGroupChannelContextSourceLOCALMESSAGEPENDINGCREATEDEnum = "2000" ;
export type SendBirdGroupChannelContextSourceLOCALMESSAGERESENDSTARTEDEnum = "2003" ;
export type SendBirdGroupChannelContextSourceMESSAGEBACKGROUNDEnum = "1002" ;
export type SendBirdGroupChannelContextSourceMESSAGECHANGELOGEnum = "1004" ;
export type SendBirdGroupChannelContextSourceMESSAGECOLLECTIONFILTERMISMATCHEnum = "2004" ;
export type SendBirdGroupChannelContextSourceMESSAGEFILLEnum = "1003" ;

