/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SendBirdSendBirdInstanceBaseChannelMessageTypeFilter } from './SendBirdSendBirdInstanceBaseChannelMessageTypeFilter';
import { HttpFile } from '../http/http';

export class SendBirdSendBirdInstanceBaseChannel {
    'messageTypeFilter'?: SendBirdSendBirdInstanceBaseChannelMessageTypeFilter;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "messageTypeFilter",
            "baseName": "MessageTypeFilter",
            "type": "SendBirdSendBirdInstanceBaseChannelMessageTypeFilter",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdSendBirdInstanceBaseChannel.attributeTypeMap;
    }

    public constructor() {
    }
}

