/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SendBirdPublicChannelFilter {
    'ALL'?: SendBirdPublicChannelFilterALLEnum;
    'PRIVATE'?: SendBirdPublicChannelFilterPRIVATEEnum;
    'PUBLIC'?: SendBirdPublicChannelFilterPUBLICEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ALL",
            "baseName": "ALL",
            "type": "SendBirdPublicChannelFilterALLEnum",
            "format": ""
        },
        {
            "name": "PRIVATE",
            "baseName": "PRIVATE",
            "type": "SendBirdPublicChannelFilterPRIVATEEnum",
            "format": ""
        },
        {
            "name": "PUBLIC",
            "baseName": "PUBLIC",
            "type": "SendBirdPublicChannelFilterPUBLICEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdPublicChannelFilter.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SendBirdPublicChannelFilterALLEnum = "all" ;
export type SendBirdPublicChannelFilterPRIVATEEnum = "private" ;
export type SendBirdPublicChannelFilterPUBLICEnum = "public" ;

