/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SendbirdExtendedMessagePayload } from './SendbirdExtendedMessagePayload';
import { HttpFile } from '../http/http';

export class SendABotMessageRequest {
    'channelUrl': string;
    'createdAt'?: number;
    'customType'?: string;
    'data'?: string;
    'dedupId'?: string;
    'extendedMessagePayload'?: SendbirdExtendedMessagePayload;
    'markAsRead'?: boolean;
    'mentioned'?: Array<string>;
    'message': string;
    'sendPush'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channelUrl",
            "baseName": "channel_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "customType",
            "baseName": "custom_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "string",
            "format": ""
        },
        {
            "name": "dedupId",
            "baseName": "dedup_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "extendedMessagePayload",
            "baseName": "extended_message_payload",
            "type": "SendbirdExtendedMessagePayload",
            "format": ""
        },
        {
            "name": "markAsRead",
            "baseName": "mark_as_read",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "mentioned",
            "baseName": "mentioned",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "sendPush",
            "baseName": "send_push",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendABotMessageRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

