/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SendBirdGroupChannel } from './SendBirdGroupChannel';
import { HttpFile } from '../http/http';

export class SendBirdGroupChannelCollection {
    'channelList'?: Array<SendBirdGroupChannel>;
    'hasMore'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channelList",
            "baseName": "channelList",
            "type": "Array<SendBirdGroupChannel>",
            "format": ""
        },
        {
            "name": "hasMore",
            "baseName": "hasMore",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdGroupChannelCollection.attributeTypeMap;
    }

    public constructor() {
    }
}

