/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SendBirdGroupChannelFilterStaticUnreadChannelFilter {
    'ALL'?: SendBirdGroupChannelFilterStaticUnreadChannelFilterALLEnum;
    'UNREAD_MESSAGE'?: SendBirdGroupChannelFilterStaticUnreadChannelFilterUNREADMESSAGEEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ALL",
            "baseName": "ALL",
            "type": "SendBirdGroupChannelFilterStaticUnreadChannelFilterALLEnum",
            "format": ""
        },
        {
            "name": "UNREAD_MESSAGE",
            "baseName": "UNREAD_MESSAGE",
            "type": "SendBirdGroupChannelFilterStaticUnreadChannelFilterUNREADMESSAGEEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdGroupChannelFilterStaticUnreadChannelFilter.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SendBirdGroupChannelFilterStaticUnreadChannelFilterALLEnum = "all" ;
export type SendBirdGroupChannelFilterStaticUnreadChannelFilterUNREADMESSAGEEnum = "unread_message" ;

