/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SendBirdMemberStateFilter {
    'ALL'?: SendBirdMemberStateFilterALLEnum;
    'INVITED'?: SendBirdMemberStateFilterINVITEDEnum;
    'INVITED_BY_FRIEND'?: SendBirdMemberStateFilterINVITEDBYFRIENDEnum;
    'INVITED_BY_NON_FRIEND'?: SendBirdMemberStateFilterINVITEDBYNONFRIENDEnum;
    'JOINED'?: SendBirdMemberStateFilterJOINEDEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ALL",
            "baseName": "ALL",
            "type": "SendBirdMemberStateFilterALLEnum",
            "format": ""
        },
        {
            "name": "INVITED",
            "baseName": "INVITED",
            "type": "SendBirdMemberStateFilterINVITEDEnum",
            "format": ""
        },
        {
            "name": "INVITED_BY_FRIEND",
            "baseName": "INVITED_BY_FRIEND",
            "type": "SendBirdMemberStateFilterINVITEDBYFRIENDEnum",
            "format": ""
        },
        {
            "name": "INVITED_BY_NON_FRIEND",
            "baseName": "INVITED_BY_NON_FRIEND",
            "type": "SendBirdMemberStateFilterINVITEDBYNONFRIENDEnum",
            "format": ""
        },
        {
            "name": "JOINED",
            "baseName": "JOINED",
            "type": "SendBirdMemberStateFilterJOINEDEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdMemberStateFilter.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SendBirdMemberStateFilterALLEnum = "all" ;
export type SendBirdMemberStateFilterINVITEDEnum = "invited_only" ;
export type SendBirdMemberStateFilterINVITEDBYFRIENDEnum = "invited_by_friend" ;
export type SendBirdMemberStateFilterINVITEDBYNONFRIENDEnum = "invited_by_non_friend" ;
export type SendBirdMemberStateFilterJOINEDEnum = "joined_only" ;

