/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SendBirdGroupChannelFilterSearchFilter {
    'searchFields'?: Array<SendBirdGroupChannelFilterSearchFilterSearchFieldsEnum>;
    'searchQuery'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "searchFields",
            "baseName": "searchFields",
            "type": "Array<SendBirdGroupChannelFilterSearchFilterSearchFieldsEnum>",
            "format": ""
        },
        {
            "name": "searchQuery",
            "baseName": "searchQuery",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdGroupChannelFilterSearchFilter.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SendBirdGroupChannelFilterSearchFilterSearchFieldsEnum = "channel_name" | "member_nickname" ;

