/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SendbirdExtendedMessagePayload } from './SendbirdExtendedMessagePayload';
import { HttpFile } from '../http/http';

export class SendbirdMessageResponseExtendedMessagePayload {
    /**
    * JSON format you want to embed in message, eq : {\"title\": \"title\", \"image\": \"https://link.to/image.jpg\"}
    */
    'customView'?: any;
    /**
    * Specifies an array of suggested replies to be sent with the message.
    */
    'suggestedReplies'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "customView",
            "baseName": "custom_view",
            "type": "any",
            "format": ""
        },
        {
            "name": "suggestedReplies",
            "baseName": "suggested_replies",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendbirdMessageResponseExtendedMessagePayload.attributeTypeMap;
    }

    public constructor() {
    }
}

