/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SendBirdGroupChannel } from './SendBirdGroupChannel';
import { HttpFile } from '../http/http';

export class SendBirdGroupChannelChangeLogs {
    'deletedChannelUrls'?: Array<string>;
    'hasMore'?: boolean;
    'token'?: string;
    'updatedChannels'?: Array<SendBirdGroupChannel>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "deletedChannelUrls",
            "baseName": "deletedChannelUrls",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "hasMore",
            "baseName": "hasMore",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedChannels",
            "baseName": "updatedChannels",
            "type": "Array<SendBirdGroupChannel>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdGroupChannelChangeLogs.attributeTypeMap;
    }

    public constructor() {
    }
}

