/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SendBirdAppInfo } from './SendBirdAppInfo';
import { SendBirdFileMessageParams } from './SendBirdFileMessageParams';
import { SendBirdGroupChannelChangeLogsParams } from './SendBirdGroupChannelChangeLogsParams';
import { SendBirdGroupChannelCollectionStatic } from './SendBirdGroupChannelCollectionStatic';
import { SendBirdGroupChannelContextSource } from './SendBirdGroupChannelContextSource';
import { SendBirdGroupChannelFilterStatic } from './SendBirdGroupChannelFilterStatic';
import { SendBirdGroupChannelParams } from './SendBirdGroupChannelParams';
import { SendBirdGroupChannelTotalUnreadMessageCountParams } from './SendBirdGroupChannelTotalUnreadMessageCountParams';
import { SendBirdMessageChangeLogsParams } from './SendBirdMessageChangeLogsParams';
import { SendBirdMessageCollectionStatic } from './SendBirdMessageCollectionStatic';
import { SendBirdMessageListParams } from './SendBirdMessageListParams';
import { SendBirdMessageMetaArray } from './SendBirdMessageMetaArray';
import { SendBirdMessageRetrievalParams } from './SendBirdMessageRetrievalParams';
import { SendBirdOpenChannelParams } from './SendBirdOpenChannelParams';
import { SendBirdOptions } from './SendBirdOptions';
import { SendBirdPollListQuery } from './SendBirdPollListQuery';
import { SendBirdPollParams } from './SendBirdPollParams';
import { SendBirdPollRetrievalParams } from './SendBirdPollRetrievalParams';
import { SendBirdPollStatic } from './SendBirdPollStatic';
import { SendBirdPollVoterListQuery } from './SendBirdPollVoterListQuery';
import { SendBirdRestrictedUserStatic } from './SendBirdRestrictedUserStatic';
import { SendBirdScheduledUserMessageParams } from './SendBirdScheduledUserMessageParams';
import { SendBirdSendBirdInstanceBaseChannel } from './SendBirdSendBirdInstanceBaseChannel';
import { SendBirdSendBirdInstanceBaseMessage } from './SendBirdSendBirdInstanceBaseMessage';
import { SendBirdThreadedMessageListParams } from './SendBirdThreadedMessageListParams';
import { SendBirdUser } from './SendBirdUser';
import { SendBirdUserMessageParams } from './SendBirdUserMessageParams';
import { HttpFile } from '../http/http';

export class SendBirdSendBirdInstance {
    'adminMessage'?: any;
    'baseChannel'?: SendBirdSendBirdInstanceBaseChannel;
    'baseMessage'?: SendBirdSendBirdInstanceBaseMessage;
    'channelHandler'?: any;
    'collectionEventSource'?: SendBirdGroupChannelContextSource;
    'connectionHandler'?: any;
    'fileMessage'?: any;
    'fileMessageParams'?: SendBirdFileMessageParams;
    'groupChannel'?: any;
    'groupChannelChangeLogsParams'?: SendBirdGroupChannelChangeLogsParams;
    'groupChannelCollection'?: SendBirdGroupChannelCollectionStatic;
    'groupChannelFilter'?: SendBirdGroupChannelFilterStatic;
    'groupChannelListQuery'?: any;
    'groupChannelParams'?: SendBirdGroupChannelParams;
    'groupChannelTotalUnreadMessageCountParams'?: SendBirdGroupChannelTotalUnreadMessageCountParams;
    'member'?: any;
    'messageChangeLogsParams'?: SendBirdMessageChangeLogsParams;
    'messageCollection'?: SendBirdMessageCollectionStatic;
    'messageFilter'?: any;
    'messageListParams'?: SendBirdMessageListParams;
    'messageMetaArray'?: SendBirdMessageMetaArray;
    'messageRetrievalParams'?: SendBirdMessageRetrievalParams;
    'openChannel'?: any;
    'openChannelParams'?: SendBirdOpenChannelParams;
    'options'?: SendBirdOptions;
    'poll'?: SendBirdPollStatic;
    'pollListQuery'?: SendBirdPollListQuery;
    'pollOption'?: any;
    'pollParams'?: SendBirdPollParams;
    'pollRetrievalParams'?: SendBirdPollRetrievalParams;
    'pollVoterListQuery'?: SendBirdPollVoterListQuery;
    'restrictedUser'?: SendBirdRestrictedUserStatic;
    'scheduledUserMessageParams'?: SendBirdScheduledUserMessageParams;
    'sessionHandler'?: any;
    'threadedMessageListParams'?: SendBirdThreadedMessageListParams;
    'user'?: any;
    'userEventHandler'?: any;
    'userMessage'?: any;
    'userMessageParams'?: SendBirdUserMessageParams;
    'appInfo'?: SendBirdAppInfo;
    'currentUser'?: SendBirdUser;
    'ekey'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "adminMessage",
            "baseName": "AdminMessage",
            "type": "any",
            "format": ""
        },
        {
            "name": "baseChannel",
            "baseName": "BaseChannel",
            "type": "SendBirdSendBirdInstanceBaseChannel",
            "format": ""
        },
        {
            "name": "baseMessage",
            "baseName": "BaseMessage",
            "type": "SendBirdSendBirdInstanceBaseMessage",
            "format": ""
        },
        {
            "name": "channelHandler",
            "baseName": "ChannelHandler",
            "type": "any",
            "format": ""
        },
        {
            "name": "collectionEventSource",
            "baseName": "CollectionEventSource",
            "type": "SendBirdGroupChannelContextSource",
            "format": ""
        },
        {
            "name": "connectionHandler",
            "baseName": "ConnectionHandler",
            "type": "any",
            "format": ""
        },
        {
            "name": "fileMessage",
            "baseName": "FileMessage",
            "type": "any",
            "format": ""
        },
        {
            "name": "fileMessageParams",
            "baseName": "FileMessageParams",
            "type": "SendBirdFileMessageParams",
            "format": ""
        },
        {
            "name": "groupChannel",
            "baseName": "GroupChannel",
            "type": "any",
            "format": ""
        },
        {
            "name": "groupChannelChangeLogsParams",
            "baseName": "GroupChannelChangeLogsParams",
            "type": "SendBirdGroupChannelChangeLogsParams",
            "format": ""
        },
        {
            "name": "groupChannelCollection",
            "baseName": "GroupChannelCollection",
            "type": "SendBirdGroupChannelCollectionStatic",
            "format": ""
        },
        {
            "name": "groupChannelFilter",
            "baseName": "GroupChannelFilter",
            "type": "SendBirdGroupChannelFilterStatic",
            "format": ""
        },
        {
            "name": "groupChannelListQuery",
            "baseName": "GroupChannelListQuery",
            "type": "any",
            "format": ""
        },
        {
            "name": "groupChannelParams",
            "baseName": "GroupChannelParams",
            "type": "SendBirdGroupChannelParams",
            "format": ""
        },
        {
            "name": "groupChannelTotalUnreadMessageCountParams",
            "baseName": "GroupChannelTotalUnreadMessageCountParams",
            "type": "SendBirdGroupChannelTotalUnreadMessageCountParams",
            "format": ""
        },
        {
            "name": "member",
            "baseName": "Member",
            "type": "any",
            "format": ""
        },
        {
            "name": "messageChangeLogsParams",
            "baseName": "MessageChangeLogsParams",
            "type": "SendBirdMessageChangeLogsParams",
            "format": ""
        },
        {
            "name": "messageCollection",
            "baseName": "MessageCollection",
            "type": "SendBirdMessageCollectionStatic",
            "format": ""
        },
        {
            "name": "messageFilter",
            "baseName": "MessageFilter",
            "type": "any",
            "format": ""
        },
        {
            "name": "messageListParams",
            "baseName": "MessageListParams",
            "type": "SendBirdMessageListParams",
            "format": ""
        },
        {
            "name": "messageMetaArray",
            "baseName": "MessageMetaArray",
            "type": "SendBirdMessageMetaArray",
            "format": ""
        },
        {
            "name": "messageRetrievalParams",
            "baseName": "MessageRetrievalParams",
            "type": "SendBirdMessageRetrievalParams",
            "format": ""
        },
        {
            "name": "openChannel",
            "baseName": "OpenChannel",
            "type": "any",
            "format": ""
        },
        {
            "name": "openChannelParams",
            "baseName": "OpenChannelParams",
            "type": "SendBirdOpenChannelParams",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "Options",
            "type": "SendBirdOptions",
            "format": ""
        },
        {
            "name": "poll",
            "baseName": "Poll",
            "type": "SendBirdPollStatic",
            "format": ""
        },
        {
            "name": "pollListQuery",
            "baseName": "PollListQuery",
            "type": "SendBirdPollListQuery",
            "format": ""
        },
        {
            "name": "pollOption",
            "baseName": "PollOption",
            "type": "any",
            "format": ""
        },
        {
            "name": "pollParams",
            "baseName": "PollParams",
            "type": "SendBirdPollParams",
            "format": ""
        },
        {
            "name": "pollRetrievalParams",
            "baseName": "PollRetrievalParams",
            "type": "SendBirdPollRetrievalParams",
            "format": ""
        },
        {
            "name": "pollVoterListQuery",
            "baseName": "PollVoterListQuery",
            "type": "SendBirdPollVoterListQuery",
            "format": ""
        },
        {
            "name": "restrictedUser",
            "baseName": "RestrictedUser",
            "type": "SendBirdRestrictedUserStatic",
            "format": ""
        },
        {
            "name": "scheduledUserMessageParams",
            "baseName": "ScheduledUserMessageParams",
            "type": "SendBirdScheduledUserMessageParams",
            "format": ""
        },
        {
            "name": "sessionHandler",
            "baseName": "SessionHandler",
            "type": "any",
            "format": ""
        },
        {
            "name": "threadedMessageListParams",
            "baseName": "ThreadedMessageListParams",
            "type": "SendBirdThreadedMessageListParams",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "User",
            "type": "any",
            "format": ""
        },
        {
            "name": "userEventHandler",
            "baseName": "UserEventHandler",
            "type": "any",
            "format": ""
        },
        {
            "name": "userMessage",
            "baseName": "UserMessage",
            "type": "any",
            "format": ""
        },
        {
            "name": "userMessageParams",
            "baseName": "UserMessageParams",
            "type": "SendBirdUserMessageParams",
            "format": ""
        },
        {
            "name": "appInfo",
            "baseName": "appInfo",
            "type": "SendBirdAppInfo",
            "format": ""
        },
        {
            "name": "currentUser",
            "baseName": "currentUser",
            "type": "SendBirdUser",
            "format": ""
        },
        {
            "name": "ekey",
            "baseName": "ekey",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdSendBirdInstance.attributeTypeMap;
    }

    public constructor() {
    }
}

