/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SendBirdRestrictionInfo {
    'description'?: string;
    'endAt'?: number;
    'restrictionType'?: SendBirdRestrictionInfoRestrictionTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "endAt",
            "baseName": "end_at",
            "type": "number",
            "format": ""
        },
        {
            "name": "restrictionType",
            "baseName": "restriction_type",
            "type": "SendBirdRestrictionInfoRestrictionTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdRestrictionInfo.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SendBirdRestrictionInfoRestrictionTypeEnum = "banned" | "muted" ;

