/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SendBirdGroupChannelChangeLogsParams {
    'customTypes'?: Array<string>;
    'includeEmpty'?: boolean;
    'includeFrozen'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "customTypes",
            "baseName": "customTypes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "includeEmpty",
            "baseName": "includeEmpty",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "includeFrozen",
            "baseName": "includeFrozen",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdGroupChannelChangeLogsParams.attributeTypeMap;
    }

    public constructor() {
    }
}

