/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SendBirdSendBirdInstanceBaseMessageReplyType {
    'ALL'?: SendBirdSendBirdInstanceBaseMessageReplyTypeALLEnum;
    'NONE'?: SendBirdSendBirdInstanceBaseMessageReplyTypeNONEEnum;
    'ONLY_REPLY_TO_CHANNEL'?: SendBirdSendBirdInstanceBaseMessageReplyTypeONLYREPLYTOCHANNELEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ALL",
            "baseName": "ALL",
            "type": "SendBirdSendBirdInstanceBaseMessageReplyTypeALLEnum",
            "format": ""
        },
        {
            "name": "NONE",
            "baseName": "NONE",
            "type": "SendBirdSendBirdInstanceBaseMessageReplyTypeNONEEnum",
            "format": ""
        },
        {
            "name": "ONLY_REPLY_TO_CHANNEL",
            "baseName": "ONLY_REPLY_TO_CHANNEL",
            "type": "SendBirdSendBirdInstanceBaseMessageReplyTypeONLYREPLYTOCHANNELEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdSendBirdInstanceBaseMessageReplyType.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SendBirdSendBirdInstanceBaseMessageReplyTypeALLEnum = "all" ;
export type SendBirdSendBirdInstanceBaseMessageReplyTypeNONEEnum = "none" ;
export type SendBirdSendBirdInstanceBaseMessageReplyTypeONLYREPLYTOCHANNELEnum = "only_reply_to_channel" ;

