/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SendBirdGroupChannelMemberListQuery {
    'hasNext'?: boolean;
    'isLoading'?: boolean;
    'limit'?: number;
    'memberStateFilter'?: SendBirdGroupChannelMemberListQueryMemberStateFilterEnum;
    'mutedMemberFilter'?: SendBirdGroupChannelMemberListQueryMutedMemberFilterEnum;
    'nicknameStartsWithFilter'?: string;
    'operatorFilter'?: SendBirdGroupChannelMemberListQueryOperatorFilterEnum;
    'order'?: SendBirdGroupChannelMemberListQueryOrderEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "hasNext",
            "baseName": "hasNext",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isLoading",
            "baseName": "isLoading",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": ""
        },
        {
            "name": "memberStateFilter",
            "baseName": "memberStateFilter",
            "type": "SendBirdGroupChannelMemberListQueryMemberStateFilterEnum",
            "format": ""
        },
        {
            "name": "mutedMemberFilter",
            "baseName": "mutedMemberFilter",
            "type": "SendBirdGroupChannelMemberListQueryMutedMemberFilterEnum",
            "format": ""
        },
        {
            "name": "nicknameStartsWithFilter",
            "baseName": "nicknameStartsWithFilter",
            "type": "string",
            "format": ""
        },
        {
            "name": "operatorFilter",
            "baseName": "operatorFilter",
            "type": "SendBirdGroupChannelMemberListQueryOperatorFilterEnum",
            "format": ""
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "SendBirdGroupChannelMemberListQueryOrderEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdGroupChannelMemberListQuery.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SendBirdGroupChannelMemberListQueryMemberStateFilterEnum = "all" | "invited_by_friend" | "invited_by_non_friend" | "invited_only" | "joined_only" ;
export type SendBirdGroupChannelMemberListQueryMutedMemberFilterEnum = "all" | "muted" | "unmuted" ;
export type SendBirdGroupChannelMemberListQueryOperatorFilterEnum = "all" | "nonoperator" | "operator" ;
export type SendBirdGroupChannelMemberListQueryOrderEnum = "member_nickname_alphabetical" | "operator_then_member_alphabetical" ;

