/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SendBirdStaticLogLevel {
    'DEBUG'?: SendBirdStaticLogLevelDEBUGEnum;
    'ERROR'?: SendBirdStaticLogLevelERROREnum;
    'INFO'?: SendBirdStaticLogLevelINFOEnum;
    'NONE'?: SendBirdStaticLogLevelNONEEnum;
    'VERBOSE'?: SendBirdStaticLogLevelVERBOSEEnum;
    'WARN'?: SendBirdStaticLogLevelWARNEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "DEBUG",
            "baseName": "DEBUG",
            "type": "SendBirdStaticLogLevelDEBUGEnum",
            "format": ""
        },
        {
            "name": "ERROR",
            "baseName": "ERROR",
            "type": "SendBirdStaticLogLevelERROREnum",
            "format": ""
        },
        {
            "name": "INFO",
            "baseName": "INFO",
            "type": "SendBirdStaticLogLevelINFOEnum",
            "format": ""
        },
        {
            "name": "NONE",
            "baseName": "NONE",
            "type": "SendBirdStaticLogLevelNONEEnum",
            "format": ""
        },
        {
            "name": "VERBOSE",
            "baseName": "VERBOSE",
            "type": "SendBirdStaticLogLevelVERBOSEEnum",
            "format": ""
        },
        {
            "name": "WARN",
            "baseName": "WARN",
            "type": "SendBirdStaticLogLevelWARNEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdStaticLogLevel.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SendBirdStaticLogLevelDEBUGEnum = "debug" ;
export type SendBirdStaticLogLevelERROREnum = "error" ;
export type SendBirdStaticLogLevelINFOEnum = "info" ;
export type SendBirdStaticLogLevelNONEEnum = "none" ;
export type SendBirdStaticLogLevelVERBOSEEnum = "verbose" ;
export type SendBirdStaticLogLevelWARNEnum = "warn" ;

