/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* User
*/
export class SendbirdUser {
    'accessToken'?: string;
    'createdAt'?: number;
    'discoveryKeys'?: Array<string>;
    'hasEverLoggedIn'?: boolean;
    'isActive'?: boolean;
    'isHideMeFromFriends'?: boolean;
    'isOnline'?: boolean;
    'isShadowBlocked'?: boolean;
    'lastSeenAt'?: number;
    'locale'?: string;
    'metadata'?: any;
    'nickname'?: string;
    'preferredLanguages'?: Array<string>;
    'profileUrl'?: string;
    'requireAuthForProfileImage'?: boolean;
    'userId'?: string;
    'state'?: SendbirdUserStateEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accessToken",
            "baseName": "access_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "discoveryKeys",
            "baseName": "discovery_keys",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "hasEverLoggedIn",
            "baseName": "has_ever_logged_in",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isActive",
            "baseName": "is_active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isHideMeFromFriends",
            "baseName": "is_hide_me_from_friends",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isOnline",
            "baseName": "is_online",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isShadowBlocked",
            "baseName": "is_shadow_blocked",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "lastSeenAt",
            "baseName": "last_seen_at",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "locale",
            "baseName": "locale",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "nickname",
            "baseName": "nickname",
            "type": "string",
            "format": ""
        },
        {
            "name": "preferredLanguages",
            "baseName": "preferred_languages",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "profileUrl",
            "baseName": "profile_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "requireAuthForProfileImage",
            "baseName": "require_auth_for_profile_image",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "SendbirdUserStateEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendbirdUser.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SendbirdUserStateEnum = "" | "invited" | "joined" ;

