/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SendBirdMessageChangeLogsParams {
    'includeMetaArray'?: boolean;
    'includeParentMessageInfo'?: boolean;
    'includeParentMessageText'?: boolean;
    'includePollDetails'?: boolean;
    'includeReaction'?: boolean;
    'includeReactions'?: boolean;
    'includeReplies'?: boolean;
    'includeThreadInfo'?: boolean;
    'replyType'?: SendBirdMessageChangeLogsParamsReplyTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "includeMetaArray",
            "baseName": "includeMetaArray",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "includeParentMessageInfo",
            "baseName": "includeParentMessageInfo",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "includeParentMessageText",
            "baseName": "includeParentMessageText",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "includePollDetails",
            "baseName": "includePollDetails",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "includeReaction",
            "baseName": "includeReaction",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "includeReactions",
            "baseName": "includeReactions",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "includeReplies",
            "baseName": "includeReplies",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "includeThreadInfo",
            "baseName": "includeThreadInfo",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "replyType",
            "baseName": "replyType",
            "type": "SendBirdMessageChangeLogsParamsReplyTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdMessageChangeLogsParams.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SendBirdMessageChangeLogsParamsReplyTypeEnum = "all" | "none" | "only_reply_to_channel" ;

