/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SendBirdPollUpdatedVoteCount } from './SendBirdPollUpdatedVoteCount';
import { HttpFile } from '../http/http';

export class SendBirdPollVoteEvent {
    'pollId'?: number;
    'ts'?: number;
    'updatedVoteCounts'?: Array<SendBirdPollUpdatedVoteCount>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pollId",
            "baseName": "pollId",
            "type": "number",
            "format": ""
        },
        {
            "name": "ts",
            "baseName": "ts",
            "type": "number",
            "format": ""
        },
        {
            "name": "updatedVoteCounts",
            "baseName": "updatedVoteCounts",
            "type": "Array<SendBirdPollUpdatedVoteCount>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdPollVoteEvent.attributeTypeMap;
    }

    public constructor() {
    }
}

