/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SendBirdThreadInfo } from './SendBirdThreadInfo';
import { HttpFile } from '../http/http';

export class SendBirdThreadInfoUpdateEvent {
    'channelType'?: string;
    'channelUrl'?: string;
    'targetMessageId'?: number;
    'threadInfo'?: SendBirdThreadInfo;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channelType",
            "baseName": "channelType",
            "type": "string",
            "format": ""
        },
        {
            "name": "channelUrl",
            "baseName": "channelUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "targetMessageId",
            "baseName": "targetMessageId",
            "type": "number",
            "format": ""
        },
        {
            "name": "threadInfo",
            "baseName": "threadInfo",
            "type": "SendBirdThreadInfo",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdThreadInfoUpdateEvent.attributeTypeMap;
    }

    public constructor() {
    }
}

