/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SBObject } from './SBObject';
import { SendBirdAppleCriticalAlertOptions } from './SendBirdAppleCriticalAlertOptions';
import { SendBirdMessageMetaArray } from './SendBirdMessageMetaArray';
import { SendBirdMessageResponse } from './SendBirdMessageResponse';
import { SendBirdOGMetaData } from './SendBirdOGMetaData';
import { SendBirdReaction } from './SendBirdReaction';
import { SendBirdThreadInfo } from './SendBirdThreadInfo';
import { SendBirdUser } from './SendBirdUser';
import { HttpFile } from '../http/http';

/**
* Message
*/
export class SendBirdBaseMessageInstance {
    'appleCriticalAlertOptions'?: SendBirdAppleCriticalAlertOptions;
    'channelType'?: string;
    'channelUrl'?: string;
    'createdAt'?: number;
    'customType'?: string;
    'data'?: string;
    'isReplyToChannel'?: boolean;
    'mentionType'?: string;
    'mentionedUsers'?: Array<SendBirdUser>;
    'messageId'?: number;
    'messageType'?: SendBirdBaseMessageInstanceMessageTypeEnum;
    'metaArray'?: SBObject;
    'metaArrays'?: Array<SendBirdMessageMetaArray>;
    'ogMetaData'?: SendBirdOGMetaData;
    'parentMessage'?: SendBirdMessageResponse;
    'parentMessageId'?: number;
    'parentMessageText'?: string;
    'reactions'?: Array<SendBirdReaction>;
    'sendingStatus'?: SendBirdBaseMessageInstanceSendingStatusEnum;
    'silent'?: boolean;
    'threadInfo'?: SendBirdThreadInfo;
    'updatedAt'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "appleCriticalAlertOptions",
            "baseName": "apple_critical_alert_options",
            "type": "SendBirdAppleCriticalAlertOptions",
            "format": ""
        },
        {
            "name": "channelType",
            "baseName": "channel_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "channelUrl",
            "baseName": "channel_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "number",
            "format": ""
        },
        {
            "name": "customType",
            "baseName": "custom_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "string",
            "format": ""
        },
        {
            "name": "isReplyToChannel",
            "baseName": "is_reply_to_channel",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "mentionType",
            "baseName": "mention_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "mentionedUsers",
            "baseName": "mentioned_users",
            "type": "Array<SendBirdUser>",
            "format": ""
        },
        {
            "name": "messageId",
            "baseName": "message_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "messageType",
            "baseName": "message_type",
            "type": "SendBirdBaseMessageInstanceMessageTypeEnum",
            "format": ""
        },
        {
            "name": "metaArray",
            "baseName": "meta_array",
            "type": "SBObject",
            "format": ""
        },
        {
            "name": "metaArrays",
            "baseName": "meta_arrays",
            "type": "Array<SendBirdMessageMetaArray>",
            "format": ""
        },
        {
            "name": "ogMetaData",
            "baseName": "og_meta_data",
            "type": "SendBirdOGMetaData",
            "format": ""
        },
        {
            "name": "parentMessage",
            "baseName": "parent_message",
            "type": "SendBirdMessageResponse",
            "format": ""
        },
        {
            "name": "parentMessageId",
            "baseName": "parent_message_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "parentMessageText",
            "baseName": "parent_message_text",
            "type": "string",
            "format": ""
        },
        {
            "name": "reactions",
            "baseName": "reactions",
            "type": "Array<SendBirdReaction>",
            "format": ""
        },
        {
            "name": "sendingStatus",
            "baseName": "sending_status",
            "type": "SendBirdBaseMessageInstanceSendingStatusEnum",
            "format": ""
        },
        {
            "name": "silent",
            "baseName": "silent",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "threadInfo",
            "baseName": "thread_info",
            "type": "SendBirdThreadInfo",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendBirdBaseMessageInstance.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SendBirdBaseMessageInstanceMessageTypeEnum = "admin" | "base" | "file" | "user" ;
export type SendBirdBaseMessageInstanceSendingStatusEnum = "canceled" | "failed" | "none" | "pending" | "succeeded" ;

