/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V3ApplicationsSettingsGlobalCustomTypeDomainFilter } from './V3ApplicationsSettingsGlobalCustomTypeDomainFilter';
import { V3ApplicationsSettingsGlobalCustomTypeImageModeration } from './V3ApplicationsSettingsGlobalCustomTypeImageModeration';
import { V3ApplicationsSettingsGlobalCustomTypeProfanityFilter } from './V3ApplicationsSettingsGlobalCustomTypeProfanityFilter';
import { V3ApplicationsSettingsGlobalCustomTypeProfanityTriggeredModeration } from './V3ApplicationsSettingsGlobalCustomTypeProfanityTriggeredModeration';
import { HttpFile } from '../http/http';

export class SetDomainFilterData {
    'domainFilter'?: V3ApplicationsSettingsGlobalCustomTypeDomainFilter;
    'profanityFilter'?: V3ApplicationsSettingsGlobalCustomTypeProfanityFilter;
    'profanityTriggeredModeration'?: V3ApplicationsSettingsGlobalCustomTypeProfanityTriggeredModeration;
    'imageModeration'?: V3ApplicationsSettingsGlobalCustomTypeImageModeration;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "domainFilter",
            "baseName": "domain_filter",
            "type": "V3ApplicationsSettingsGlobalCustomTypeDomainFilter",
            "format": ""
        },
        {
            "name": "profanityFilter",
            "baseName": "profanity_filter",
            "type": "V3ApplicationsSettingsGlobalCustomTypeProfanityFilter",
            "format": ""
        },
        {
            "name": "profanityTriggeredModeration",
            "baseName": "profanity_triggered_moderation",
            "type": "V3ApplicationsSettingsGlobalCustomTypeProfanityTriggeredModeration",
            "format": ""
        },
        {
            "name": "imageModeration",
            "baseName": "image_moderation",
            "type": "V3ApplicationsSettingsGlobalCustomTypeImageModeration",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SetDomainFilterData.attributeTypeMap;
    }

    public constructor() {
    }
}

