/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SetDomainFilterDataDomainFilter {
    'domains'?: Array<string>;
    'type'?: number;
    'shouldCheckGlobal'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "domains",
            "baseName": "domains",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "number",
            "format": ""
        },
        {
            "name": "shouldCheckGlobal",
            "baseName": "should_check_global",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SetDomainFilterDataDomainFilter.attributeTypeMap;
    }

    public constructor() {
    }
}

