/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UpdateAUserRequest {
    'discoveryKeys'?: Array<string>;
    'isActive'?: boolean;
    'issueAccessToken'?: boolean;
    'lastSeenAt'?: number;
    'leaveAllWhenDeactivated'?: boolean;
    'nickname'?: string;
    'preferredLanguages'?: Array<string>;
    'profileFile'?: HttpFile;
    'profileUrl'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "discoveryKeys",
            "baseName": "discovery_keys",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "isActive",
            "baseName": "is_active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "issueAccessToken",
            "baseName": "issue_access_token",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "lastSeenAt",
            "baseName": "last_seen_at",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "leaveAllWhenDeactivated",
            "baseName": "leave_all_when_deactivated",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "nickname",
            "baseName": "nickname",
            "type": "string",
            "format": ""
        },
        {
            "name": "preferredLanguages",
            "baseName": "preferred_languages",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "profileFile",
            "baseName": "profile_file",
            "type": "HttpFile",
            "format": "binary"
        },
        {
            "name": "profileUrl",
            "baseName": "profile_url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateAUserRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

