/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class V3GroupChannelsChannelUrlScheduledMessagesScheduledMessageIdDeleteRequest {
    /**
    * Specifies the type of the message. The value of MESG represents a text message.
    */
    'messageType'?: string;
    /**
    * Specifies the user ID of the sender.
    */
    'userId'?: string;
    /**
    * Specifies the content of the message.
    */
    'message'?: string;
    /**
    * Depending on the file upload method, this specifies the data of the file to upload to the Sendbird server either in raw binary format or by the file's location. When sending a request containing a file, you must change the value of the content-type header to multipart/form-data; boundary={your_unique_boundary_string} in the request. The code examples of HTTP multipart request and cURL are provided below the tables for your reference. If this file property is specified, the url property is not required. This doesn't allow a converted base64-encoded string from a file as its value.
    */
    'file'?: string;
    /**
    * Specifies the URL of the file hosted on the server of your own or other third-party companies. If this url property is specified, the file property is not required.
    */
    'url'?: string;
    /**
    * The specified time that indicates when to send the message, in Unix milliseconds format. Since messages are scheduled in minutes, values less than seconds are discarded. The specified time can be between 5 minutes and 43,200 minutes (30 days) from the current time.
    */
    'scheduledAt'?: number;
    /**
    * Specifies a custom message type used for message grouping. The length is limited to 128 characters. * Custom types are also used to segment metrics within Sendbird's Advanced analytics, which enables the sub-classification of data views.
    */
    'customType'?: string;
    /**
    * Specifies additional message information such as custom font size, font type, or JSON formatted string.
    */
    'data'?: string;
    /**
    * Determines whether to send a push notification of the message to the channel members. This property only applies to group channels. (Default is true)
    */
    'sendPush'?: boolean;
    /**
    * Specifies the mentioning method that indicates which user receives a notification of the message. Acceptable values are users and channels. If set to users, only the users specified in the mentioned_user_ids property below are notified. If set to channels, all users in the channel are notified. (Default = users)
    */
    'mentionType'?: string;
    /**
    * Specifies an array of one or more IDs of the users who will receive a notification of the message.
    */
    'mentionedUserIds'?: Array<string>;
    /**
    * Determines whether to send a message without updating some of the following channel properties. If set to true, the channel's last_message is updated only for the sender while its unread_message_count remains unchanged for all channel members. Also, a push notification isn't sent to the users receiving the message. If the message is sent to a hidden channel, the channel remains hidden. (Default is false)
    */
    'isSilent'?: boolean;
    /**
    * Determines whether to mark the message as read for the sender. If set to false, then the sender's unread_count and read_receipt remain unchanged after the message is sent. (Default is true)
    */
    'markAsRead'?: boolean;
    /**
    * Specifies an array of one or more JSON objects consisting of key-values items that store additional message information. Items are saved and returned in the exact order they've been specified.
    */
    'sortedMetaarray'?: Array<any>;
    /**
    * Specifies a unique ID for the message created by another system. In general, this property is used to prevent the same message data from getting inserted when migrating messages from another system to the Sendbird server. If specified, the server performs a duplicate check using the property value.
    */
    'dedupId'?: string;
    /**
    * Specifies the bundle ID of the client app in order to send a push notification to iOS devices. You can find this in Settings > Chat > Notifications > Push notification services on Sendbird Dashboard.
    */
    'apnsBundleId'?: string;
    /**
    * Specifies options that support Apple's critical alerts and checks whether the message is a critical alert.
    */
    'appleCriticalAlertOptions'?: any;
    /**
    * Specifies the name of a sound file that is used for critical alerts.
    */
    'sound'?: string;
    /**
    * Specifies the volume of the critical alert sound. The volume ranges from 0.0to 1.0, which indicates silent and full volume, respectively. (Default = 1.0)
    */
    'volume'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "messageType",
            "baseName": "message_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "file",
            "baseName": "file",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "scheduledAt",
            "baseName": "scheduled_at",
            "type": "number",
            "format": ""
        },
        {
            "name": "customType",
            "baseName": "custom_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "string",
            "format": ""
        },
        {
            "name": "sendPush",
            "baseName": "send_push",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "mentionType",
            "baseName": "mention_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "mentionedUserIds",
            "baseName": "mentioned_user_ids[]",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "isSilent",
            "baseName": "is_silent",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "markAsRead",
            "baseName": "mark_as_read",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sortedMetaarray",
            "baseName": "sorted_metaarray",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "dedupId",
            "baseName": "dedup_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "apnsBundleId",
            "baseName": "apns_bundle_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "appleCriticalAlertOptions",
            "baseName": "apple_critical_alert_options",
            "type": "any",
            "format": ""
        },
        {
            "name": "sound",
            "baseName": "sound",
            "type": "string",
            "format": ""
        },
        {
            "name": "volume",
            "baseName": "volume",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V3GroupChannelsChannelUrlScheduledMessagesScheduledMessageIdDeleteRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

