/**
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class V3PollsPollIdDeleteRequest {
    /**
    * Specifies the URL of the channel. If channel_type is specified, channel_url must be specified as well.
    */
    'channelUrl'?: string;
    /**
    * Specifies the type of the channel. Either open_channels or group_channels.
    */
    'channelType'?: string;
    /**
    * Determines whether to show a partial list of voters for each option. If set to true, the option resources inside the response include the partial_voter_list property which shows up to ten voters.
    */
    'showPartialVoterList'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channelUrl",
            "baseName": "channel_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "channelType",
            "baseName": "channel_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "showPartialVoterList",
            "baseName": "show_partial_voter_list",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V3PollsPollIdDeleteRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

