/**
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListDataExportsByMessageChannelOrUserResponseFile } from './ListDataExportsByMessageChannelOrUserResponseFile';
import { HttpFile } from '../http/http';

export class ViewGdprRequestByIdResponse {
    'requestId'?: string;
    'action'?: string;
    'status'?: string;
    'userId'?: string;
    'files'?: ListDataExportsByMessageChannelOrUserResponseFile;
    'userIds'?: Array<string>;
    'channelDeleteOption'?: string;
    'createdAt'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "files",
            "baseName": "files",
            "type": "ListDataExportsByMessageChannelOrUserResponseFile",
            "format": ""
        },
        {
            "name": "userIds",
            "baseName": "user_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "channelDeleteOption",
            "baseName": "channel_delete_option",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ViewGdprRequestByIdResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

